### ISSUE TITLE
ModuleNotFoundError: No module named 'ailia'

### ISSUE THREAD

**Issue by innovationcreators** [axinc-ai/ailia-models#100]
I have tried HRNet_segmentation from ailia_models but when i'd run the below command to get the output for sample image I got the following error.

command - python3 hrnet_segmentation.py

error - 
Traceback (most recent call last):
  File "hrnet_segmentation.py", line 8, in <module>
    import ailia
ModuleNotFoundError: No module named 'ailia'

I have tried to find the ailia module but I didn't get where it is placed, so could you please help me with the solution for this?

Thanks.

**Comment by kyakuno** [comment]
You can download a free evaluation version that allows you to evaluate the ailia SDK for 30 days. Please download from the trial link below.

https://ailia.jp/en/
https://ailia.jp/en/trial/
