### ISSUE TITLE
Change deepsort argument

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#104]
Now -i option is used for video input.
For consistency, please change to -v option.

**Comment by kyakuno** [comment]
Example:
python3 deepsort.py -v input.mp4
python3 deepsort.py -v 0

**Comment by sngyo** [comment]
`-i`が基本はmain input となるように考えていたので画像比較モードは引き続き`-p`にしてあります．

videoは`-v`に修正しました．
