### ISSUE TITLE
ADD SSR-Net

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1046]
https://github.com/shamangary/SSR-Net
Apache

**Comment by ooe1123** [comment]
学習モデル公開なし
学習に用いるデータセットのうち、[Morph2 dataset](https://www.faceaginggroup.com/)がリンク切れ。

**Comment by ooe1123** [comment]
Pytorchによる実装（ライセンス表記なし）
https://github.com/oukohou/SSR_Net_Pytorch

**Comment by kyakuno** [comment]
#66 と重複。
