### ISSUE TITLE
Too many models at the top level

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#108]
今後モデル数が増加していくことを考慮すると，カテゴリーレベルでサブディレクトリをつくるなどしたほうが見やすくなるかもしれない？

- 見やすくなる
- カテゴリーごとのREADMEでより詳しいモデル紹介ができる

この改変を行うタイミングで，現状直置きしているモデルファイル(`onnx`, `prototxt`)を`models`もしくは`chekckpoints`ディレクトリを各モデル下に用意する方式に変えたい．特に複数モデルを使用するサンプルや複数の重み選択肢(efficient-netなど)があるサンプルでディレクトリがごちゃごちゃしてきて見づらくなるのを防ぐため．

**Comment by kyakuno** [comment]
はい、サブディレクトリを置く構成に変更頂いて問題ありません。

**Comment by kyakuno** [comment]
対応しました。
