### ISSUE TITLE
ADD RVC Voice Changer

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1096]
AIを使用したボイスチェンジャー。
https://github.com/liujing04/Retrieval-based-Voice-Conversion-WebUI

**Comment by kyakuno** [comment]
https://eyatu-vrc.hatenablog.com/entry/2023/04/06/193512

**Comment by srpkdyy** [comment]
fairseqのhubertモデルが内部で用いられているが、ONNXエクスポートが難しい

**Comment by kyakuno** [comment]
RVCのコアモデルはONNXに変換できそうに思われる
https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_ja_latest.md

**Comment by kyakuno** [comment]
推論サンプルの中でhubertをloadしている
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/infer-web.py

**Comment by kyakuno** [comment]
hubertは音声におけるbertのような表現学習モデル
https://techblog.yahoo.co.jp/entry/2023032930418574/

**Comment by kyakuno** [comment]
hubertをonnxにエクスポートすると推論できない
https://github.com/onnx/onnx/issues/3907

**Comment by kyakuno** [comment]
latestのtorchだとエクスポートと推論ができるとのこと
https://github.com/pytorch/pytorch/issues/70289

**Comment by kyakuno** [comment]
@ooe1123 現在、取り込まれているモデルの後に、こちらのモデルの変換をお願いしてもよいでしょうか。

**Comment by ooe1123** [comment]
https://github.com/pytorch/pytorch/issues/98190#issuecomment-1546200836

**Comment by ooe1123** [comment]
F.scaled_dot_product_attentionのエクスポートは、現時点でNightly版で対応されたとのこと。
https://github.com/pytorch/pytorch/issues/98190#issuecomment-1546200836

**Comment by ooe1123** [comment]
RVC WebUIの導入
https://zenn.dev/kaeru39/articles/c13b45726ca668

**Comment by kyakuno** [comment]
アーキテクチャとしてはPCM入力、PCM出力となっている。

1. 入力音声を16kHzのrange(-1,+1)のモノラル音声にする（4secの場合、(60736,))
2. highpassフィルタを0位相フィルタで適用（filtfilt）
3. hubertで特徴ベクトルを取得（feat (1, 156736), output (1,489,256))
4. 特徴ベクトルにinterpolateを適用して2倍の長さにする
5. vcで音声変換 (feat (1, 978, 256), output (1, 1, 391200)
6. 出力音量を正規化

**Comment by kyakuno** [comment]
リアルタイムモードにも対応したいため、バッチとリアルタイムで同じONNXが使用できるかを確認する必要がある。
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/blob/main/rvc_for_realtime.py

**Comment by kyakuno** [comment]
VCモデルのONNX変換はWEBUIにも搭載されている。
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

**Comment by kyakuno** [comment]
MITライセンスのVCモデル。
https://chihaya369.booth.pm/items/4701666

**Comment by kyakuno** [comment]
if_f0はpitch guidanceで歌声用にpitchを追加情報として与えるために追加されている気がする。

**Comment by kyakuno** [comment]
4secの音声ファイルのM2での処理時間。ailia SDK 1.2.15

|モデル|MPS|BLAS|
|-----|-----|-----|
|hubert 1st|8655ms|2561ms|
|hubert 2nd|8278ms|2306ms|
|vc 1st| 8800ms|7737ms|
|vc 2nd|7952ms|6299ms|

**Comment by kyakuno** [comment]
MPS Profile

hubert

```
====Profile(Grouped by LayerType)====
LayerType	TotalPredictTime(Average)[us]	TimeRatio[%]
MatMul_DNN	7843389	93.31
Convolution1D/Gelu[Fused]_DNN	329624	3.92
Convolution1D/Gelu[Fused]	309551	3.68
Eltwise_DNN	84765	1.01
Convolution1D_DNN	64120	0.76
ReduceMean_DNN	62086	0.74
```

vc

```
LayerType	TotalPredictTime(Average)[us]	TimeRatio[%]
Convolution1D_DNN	3377697	40.56
Convolution1D	3290021	39.50
Convolution1D/PReLU[Fused]_DNN	3207996	38.52
Convolution1D/PReLU[Fused]	2983992	35.83
Eltwise	492447	5.91
PReLU	297115	3.57
Deconvolution_DNN	262809	3.16
Eltwise_DNN	245986	2.95
```

**Comment by kyakuno** [comment]
BLAS Profile

hubert

```
====Profile(Grouped by LayerType)====
LayerType	TotalPredictTime(Average)[us]	TimeRatio[%]
MatMul_DNN	1920693	79.86
MatMul	1876271	78.01
Convolution1D/Gelu[Fused]	335134	13.93
Eltwise_DNN	94547	3.93
ReduceMean_DNN	47363	1.97
Convolution1D_DNN	45820	1.91
Gemm_DNN	44634	1.86
```

vc

```
====Profile(Grouped by LayerType)====
LayerType	TotalPredictTime(Average)[us]	TimeRatio[%]
Convolution1D	3063279	46.36
Convolution1D/PReLU[Fused]	2948313	44.62
Deconvolution	188019	2.85
Eltwise	128596	1.95
MatMul	112141	1.70
PReLU	59852	0.91
```

**Comment by kyakuno** [comment]
hubertはmatmulネック、vcはConv1Dネック。

**Comment by kyakuno** [comment]
4secの音声ファイルのRTX3080での処理時間。ailia SDK 1.2.15。

|モデル|cuDNN FP32|
|-----|-----|
|hubert 1st|1437ms|
|hubert 2nd|275ms|
|vc 1st| 1144ms|
|vc 2nd|288ms|

PCであればリアルタイム処理が可能。

**Comment by kyakuno** [comment]
WebUIの起動。

```
git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI
pip3 install -r requirements.txt
python3 infer_web.py
```

![webui](https://github.com/axinc-ai/ailia-models/assets/38881041/55662a4b-a6ad-4c62-8a90-8dfb894de527)

**Comment by kyakuno** [comment]
気になる点
・filtfiltで16kHzのhigh pass filterをかけているが入力音声が16kHzだと不要ではないか？

**Comment by kyakuno** [comment]
C++から呼び出す場合、16kHzのPCMから1つ目のモデルでEmbeddingを取得して、2つ目のモデルでPCMを取得するだけでシンプルに実装できそう。

**Comment by kyakuno** [comment]
feats = F.interpolate(feats.permute(0, 2, 1), scale_factor=2).permute(0, 2, 1)
は、
　interpolate in torch.Size([1, 489, 256])
　interpolate out torch.Size([1, 978, 256])
のように、axis=1をnearestで2倍にコピーする操作である。

下記でも等価になる。

```
    new_feats = np.zeros((feats.shape[0], feats.shape[1]*2, feats.shape[2]))
    for i in range(feats.shape[1]):
        new_feats[:,i*2+0,:] = feats[:,i,:]
        new_feats[:,i*2+1,:] = feats[:,i,:]
    feats = new_feats
```

下記で計算した誤差は0になる。

```
print("diff", (interp_feats - feats).mean())
```

**Comment by kyakuno** [comment]
RMSは下記のコードで計算可能。

```
    rms1 = librosa.feature.rms(
        y=audio0, frame_length=16000 // 2 * 2, hop_length=16000 // 2
    )  # 每半秒一个点

    import math
    rms2 = []
    i = 0
    while i < len(audio0):
        sum = 0
        for j in range(16000 // 2 * 2):
            if i + j - 16000 // 2 >= 0 and i + j - 16000 // 2 < len(audio0):
                sum = sum + audio0[i + j - 16000 // 2] * audio0[i + j - 16000 // 2]
        i = i + 16000 //2
        rms2.append(math.sqrt(sum / (16000 // 2 * 2)))
```

```
rms1 [[0.01186692 0.03842403 0.07738604 0.09538703 0.11221342 0.09029565
  0.00377364 0.09029192 0.11220899 0.09538583 0.07739243 0.03843572
  0.01580535 0.01053577 0.0083064  0.01405562 0.03136    0.06526884
  0.09713326 0.11689314]]
recalc rms1 [0.011866915683046389, 0.03842402383352823, 0.07738604487145795, 0.09538702655233344, 0.1122134129345262, 0.09029564310712612, 0.0037736419053470208, 0.09029190999923685, 0.11220899426454611, 0.09538583212138613, 0.07739242836008103, 0.03843572278584739, 0.015805346160338015, 0.010535767466201143, 0.008306403196957655, 0.014055619783892297, 0.03135999664088785, 0.06526883390625657, 0.09713326339263806, 0.11689313597392988]
```

**Comment by kyakuno** [comment]
RVCのモデルサイズはhubert_baseが293.5MB、vcが110.2MB。
4secで消費メモリは1.49GB程度。

**Comment by kyakuno** [comment]
音声ファイルによってはailiaでもonnx runtimeでも下記のエラーになることがある。入力長に何か制約がありそう。

```
+ error detail : Layer:/final_proj/MatMul_output_0(MatMul_DNN) Error:This layer is not support inference with empty blobs.

RuntimeError: Input and output sizes should be greater than 0, but got input (W: 0) and output (W: 0)
```

**Comment by kyakuno** [comment]
156736 -> OK
233440 -> OK
233937 -> NG

**Comment by kyakuno** [comment]
40secの音声でもエラーになるので、入力長が一定以上になると動かない気がする。

**Comment by kyakuno** [comment]
hubertのONNXエクスポート時の音声ファイルに影響されている可能性があるかどうか。

**Comment by kyakuno** [comment]
Transposeまでは正しい値が取れていて、Sliceで次元数が0になってしまっている。

```
Idx 2131 /encoder/Transpose_5_output_0 (1, 730, 768)
Idx 2132 /encoder/Neg_output_0 ()
Idx 2133 /encoder/Constant_51_output_0 (1,)
Idx 2134 /encoder/Unsqueeze_6_output_0 (1,)
Idx 2135 /encoder/Constant_50_output_0 (1,)
Idx 2136 /encoder/Constant_49_output_0 (1,)
Idx 2137 /encoder/Constant_52_output_0 (1,)
Idx 2138 /encoder/Slice_5_output_0 (1, 0, 768)
Idx 2139 onnx::MatMul_2842 (768, 256)
```

**Comment by kyakuno** [comment]
/encoder/Unsqueeze_6_output_0 <- "/encoder/Neg_output_0" <- "/encoder/Cast_2_output_0" <- "/encoder/Sub_output_0" <- "/encoder/Mul_3_output_0"

**Comment by kyakuno** [comment]
/encoder/Mul_3_output_0は730.0が入っていて、/encoder/Sub_output_0が0.0になっている。
/encoder/Cast_1_output_0が730.0なので、Subで0になってしまう。

**Comment by kyakuno** [comment]
正常に推論できるサンプルだと、/encoder/Unsqueeze_6_output_0は-1が入っていて、/encoder/Sub_output_0は1.0。
/encoder/Mul_3_output_0が730.0で、/encoder/Cast_1_output_0が729.0になっている。

**Comment by kyakuno** [comment]
A % 2 - Aをして、無理やり-1を作って、Sliceのend_indicesに入れて、全ての出力を出すという不思議なONNXになっている。この最後のSliceは入力Shapeをそのまま出力するものであり、不要ではないかと思われる。

![slice](https://github.com/axinc-ai/ailia-models/assets/38881041/c12b7770-041e-4653-9aea-55815a45a1c3)

**Comment by kyakuno** [comment]
@ooe1123 hubertのエクスポート時に、何らかのコードで、MatMulの前にSliceが入ってしまっているようでして、エクスポート時にこれを削除することは可能でしょうか？

**Comment by ooe1123** [comment]
@kyakuno 
当該のSlice処理は、モデルが利用している外部モジュールの以下の箇所に該当するようです。
https://github.com/facebookresearch/fairseq/blob/main/fairseq/models/wav2vec/wav2vec2.py#L1144-L1154

paddingがある場合とない場合とでif文による分岐が発生しており、どちらかのパターンにしか対応できていないモデルになってしまっているようですね。
分岐が発生しない形に修正できないか、検討してみますが、難しい場合はモデルに入力するテンソルのサイズを固定するという対応が必要かもしれません。

**Comment by kyakuno** [comment]
if_f0 = Trueの場合は、net_gにpitchとpitchfの引数が加わる。
pitchはhubertのfeatureのlengthだけ使用する。

**Comment by kyakuno** [comment]
protectが有効な場合、下記の式で補正する。この時、featsはfaissを適用したもの、feats0はfaissを適用しないものである。

```
    if protect < 0.5 and pitch is not None and pitchf is not None:
        pitchff = np.copy(pitchf)
        pitchff[pitchf > 0] = 1
        pitchff[pitchf < 1] = protect
        pitchff = np.expand_dims(pitchff, axis=-1)
        feats = feats * pitchff + feats0 * (1 - pitchff)
```

**Comment by kyakuno** [comment]
faissは、k=8の近いfeature vectorを取得し、元のfeature vectorに重み付けする機能。

**Comment by ArEnSc** [comment]
#feats = hubert.get_blob_data(hubert.find_blob_index_by_name("/encoder/Slice_5_output_0")) # v2 : 768
            elif args.version == 2:
bug in the rvc.py 

does not actually get that layer from onxx model
