### ISSUE TITLE
Whisper - onnx error

### ISSUE THREAD

**Issue by ysnylmzz** [axinc-ai/ailia-models#1136]
Hi , I am trying to run whisper on onnx mode. I got error while loading model. I didnt see any requirement file . Can u tell me onnxruntime version ?
![Screenshot 2023-05-18 082901](https://github.com/axinc-ai/ailia-models/assets/45534983/4fe277fc-c432-4475-98aa-808edb3633ae)

**Comment by kyakuno** [comment]
ONNX Runtime not support mean variance normalization on GPU. So please use `--normal` option.

```
python3 whisper.py --onnx --normal
```
