### ISSUE TITLE
No Package named "arg_utils"

### ISSUE THREAD

**Issue by caelia13** [axinc-ai/ailia-models#1139]
When downloading and running animalpose.py, there is no other package in repo called "arg_utils". There is a note that "arg_utils" is named as such in order to avoid a conflict with the PyPi package "utils", but there is no documentation on what/where "arg_utils" is. The resulting error is as shown:

ModuleNotFoundError: No module named 'arg_utils'

**Comment by kyakuno** [comment]
@caelia13 This one.
https://github.com/axinc-ai/ailia-models/blob/master/util/arg_utils.py
Please check arg_util.py exists in the util folder.
