### ISSUE TITLE
downsize model : crowdcount

### ISSUE THREAD

**Issue by kzmogi** [axinc-ai/ailia-models#116]
The crowdcount.onnx has unused initializers. Follwing entries are never used.

```
  initializer {
      dims: 512
      data_type: 1
      name: "CCN.hl_prior_fc1.fc.bias"
  }
  initializer {
      dims: 512
      dims: 4096
      data_type: 1
      name: "CCN.hl_prior_fc1.fc.weight"
  }
  initializer {
      dims: 1
      data_type: 1
      name: "CCN.hl_prior_fc1.relu.weight"
  }
  initializer {
      dims: 256
      data_type: 1
      name: "CCN.hl_prior_fc2.fc.bias"
  }
  initializer {
      dims: 256
      dims: 512
      data_type: 1
      name: "CCN.hl_prior_fc2.fc.weight"
  }
  initializer {
      dims: 1
      data_type: 1
      name: "CCN.hl_prior_fc2.relu.weight"
  }
  initializer {
      dims: 10
      data_type: 1
      name: "CCN.hl_prior_fc3.fc.bias"
  }
  initializer {
      dims: 10
      dims: 256
      data_type: 1
      name: "CCN.hl_prior_fc3.fc.weight"
  }
  initializer {
      dims: 1
      data_type: 1
      name: "CCN.hl_prior_fc3.relu.weight"
  }
```

Through ailia/onnx_optimizer.py, these entries are striped and model size changed 1/10 (9,821,328  to 894,009) .

**Comment by kyakuno** [comment]
```
mbook10:crowdcount-cascaded-mtl kyakuno$ python3 onnx_optimizer.py crowdcount.onnx
+ creating crowdcount.opt.onnx
  from crowdcount.onnx ...
  * info : supported model opset_version=(10) 
  [i] report : remove 14 Unsqueeze node.
  now analysing the model using shape inference :
  [i] report : convert 0 node to initializer
```

**Comment by kyakuno** [comment]
normal
INFO model_utils.py (67) : ONNX file and Prototxt file are prepared!
 INFO crowdcount-cascaded-mtl.py (52) : test.jpeg
 INFO crowdcount-cascaded-mtl.py (69) : BENCHMARK mode
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 2521 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 307 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 262 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 273 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 241 ms
 INFO crowdcount-cascaded-mtl.py (99) : saved at : result.png
 INFO crowdcount-cascaded-mtl.py (101) : Script finished successfully.
opt
mbook10:crowdcount-cascaded-mtl kyakuno$ python3 crowdcount-cascaded-mtl.py -b
 INFO utils.py (13) : Start!
 INFO utils.py (146) : env_id: 2
 INFO model_utils.py (67) : ONNX file and Prototxt file are prepared!
 INFO crowdcount-cascaded-mtl.py (52) : test.jpeg
 INFO crowdcount-cascaded-mtl.py (69) : BENCHMARK mode
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 864 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 330 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 232 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 231 ms
 INFO crowdcount-cascaded-mtl.py (74) : 	ailia processing time 231 ms
 INFO crowdcount-cascaded-mtl.py (99) : saved at : result.png
 INFO crowdcount-cascaded-mtl.py (101) : Script finished successfully.

**Comment by kyakuno** [comment]
9.8MB -> 898KB
