### ISSUE TITLE
ADD facemesh v2

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1181]
facemeshがv2になったようなので、変換できないか検討する。
http://ossan-engineer.blogspot.com/2023/06/facelandmarkdetection.html

**Comment by kyakuno** [comment]
https://developers.google.com/mediapipe/solutions/vision/face_landmarker

**Comment by kyakuno** [comment]
https://storage.googleapis.com/mediapipe-assets/Model%20Card%20MediaPipe%20Face%20Mesh%20V2.pdf

**Comment by kyakuno** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/390_BlendshapeV2

**Comment by kyakuno** [comment]
https://github.com/PINTO0309/facemesh_onnx_tensorrt/issues/4

**Comment by kyakuno** [comment]
BlendshapeV2をエクスポートする。

**Comment by ooe1123** [comment]
フレームワークビルド参考サイト
https://qiita.com/appletea0116/items/14d54232bb225e822744

**Comment by ooe1123** [comment]
Face landmark detectionのモデルグラフ
https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/vision/face_landmarker/face_landmarker_graph.cc#L412-L564

**Comment by kyakuno** [comment]
facemeshv1との違い
・detectorはbalzefaceのchannel_last版になっている
　・blazefaceが(3,128,128)の入力、(1,896,16) + (1,896,1)の出力に対して、
　　facedetectorが(128,128,3)の入力、(1,896,16) + (1,896,1)の出力
　・後処理は同じ
・landmarkは画像サイズが異なり、出力のキーポイントも増えている
　・facemeshv1が(3,192,192)の入力、(1,1404)の出力に対して、
　　facemeshv1が(256,256,3)の入力、(1,1434)の出力
　・後処理は座標をAffine変換していくだけで同じに見える

**Comment by kyakuno** [comment]
・blendshapeはピクセル座標のランドマーク集合を入力として、
　ラベルごとのscoreが出力される

**Comment by kyakuno** [comment]
@ooe1123 blendshapeへの入力につきまして、下記のコードで、入力画像サイズを乗算して、ピクセル座標で与えているかと思います。この処理に対応するMediaPipeのコードの場所を教えていただくことは可能でしょうか。

気になっているのは、
・入力画像のピクセル座標なのか、FaceMeshのピクセル座標なのか
・AI出力直後の座標系の方がいいのか、顔角度で回転したあとの座標系の方がいいのか
というところで、現在は、
・入力画像のピクセル座標
・顔角度で回転した後の座標系
なのですが、
・FaceMeshのピクセル座標（*256）
・顔角度で回転する前の座標系（正面）
の方が素直な気もしまして、気になっています。

```
def face_blendshapes(net, landmarks, image_size, onnx):
    landmarks = landmarks[LandmarksSubsetIdxs]

    h, w = image_size
    for lmk in landmarks:
        lmk[0] *= w
        lmk[1] *= h

    input = landmarks[:, :2]
    input = np.expand_dims(input, axis=0)
    input = input.astype(np.float32)
    if not onnx:
        output = net.predict([input])
    else:
        output = net.run(None, {'serving_default_input_points:0': input})
    score = output[0]

    return score
```

**Comment by ooe1123** [comment]
@kyakuno 
blendshapeのフローグラフを組み立てている箇所は以下になります。
https://github.com/google/mediapipe/blob/master/mediapipe/tasks/cc/vision/face_landmarker/face_blendshapes_graph.cc#L298-L307

ここのConvertLandmarksToTensor()関数の中で使っている
LandmarksToTensorCalculatorの処理はこちらになります。
https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/landmarks_to_tensor_calculator.cc#L114-L152

実際のスケーリングを行っているのはこちらです。https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tensor/landmarks_to_tensor_calculator.cc#L67-L92

**Comment by kyakuno** [comment]
情報ありがとうございます！確認します。

**Comment by kyakuno** [comment]
mediapipeの出力

![mediapipe_bar_graph](https://github.com/axinc-ai/ailia-models/assets/38881041/01838781-a2b2-471b-b406-b3ec7dc6b8ec)

ailiaの出力

![ailia_bar_graph](https://github.com/axinc-ai/ailia-models/assets/38881041/b8a445a8-7cbf-401a-8605-847f6307e4cb)

ailiaでfacemeshの出力を変形せずにそのままblendshapeに入れた出力

![ailia_bar_graph_direct](https://github.com/axinc-ai/ailia-models/assets/38881041/5f69bb6b-3149-41ec-a504-932b8cb8a715)

**Comment by kyakuno** [comment]
demo.jpgの画像を90度回転された場合

mediapipeの出力

![mediapipe_bar_graph2](https://github.com/axinc-ai/ailia-models/assets/38881041/0bff470b-b4ea-4443-b42c-4f3ea11c7b21)

ailiaの出力

![ailia_bar_graph2](https://github.com/axinc-ai/ailia-models/assets/38881041/c69b83ce-f0bd-4cbd-9215-56491e19d48a)

ailiaでfacemeshの出力を変形せずにそのままblendshapeに入れた出力

![ailia_bar_graph_direct2](https://github.com/axinc-ai/ailia-models/assets/38881041/f8614eab-c3de-4bb0-8ecc-eca6402500b0)

**Comment by kyakuno** [comment]
現状のコードの通り、ピクセル座標を入力するのが正しい模様。

**Comment by kyakuno** [comment]
blendshapeのモデルの最初に、平均除去と正規化が入っているので、ここでピクセル座標から内部座標への変換が行われているみたいですね。

![blendshape](https://github.com/axinc-ai/ailia-models/assets/38881041/c0e9f287-38da-4823-bb51-7ae184870c97)
