### ISSUE TITLE
ADD glasses-removal-gan

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#119]
https://github.com/lecomte/glasses-removal-gan

**Comment by kyakuno** [comment]
Or https://github.com/MingtaoGuo/Deep-Feature-Interporlation-Face-Attribute-manipulation-Glasses-Remove-Youth2Senior-etc.-TensorFlow

**Comment by prolleytroblems** [comment]
Exported the first model, but performance is poor. The second model cannot be exported due to relying on activation maximization.
