### ISSUE TITLE
ADD RNNoise

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1224]
https://github.com/xiph/rnnoise
https://jmvalin.ca/demo/rnnoise/

**Comment by yuki399** [comment]
C言語で作られているためonnxのエクスポートできない

**Comment by kyakuno** [comment]
学習コードはkerasなため、kerasからtensorflow2onnxで変換できないかと考えています。
https://gitlab.xiph.org/xiph/rnnoise/-/blob/master/training/rnn_train.py?ref_type=heads

**Comment by ooe1123** [comment]
推論
```
examples/rnnoise_demo babble_15dB.wav xxx.pcm
sox -t raw -b 16 -e signed -c 1 -r 48000 xxx.pcm output.wav
```

**Comment by ooe1123** [comment]
https://github.com/xiph/rnnoise/issues/79
こちらのスクリプトから、.pbファイルを作成することが可能。
tensorflwo2では動作しないため、古いバージョンである必要がある。

Python 3.7.0
Keras==2.1.2
tensorflow==1.15.0

**Comment by ooe1123** [comment]
onnx変換

```
python -m tf2onnx.convert --graphdef rnnoise.pb --output xxx.onnx --opset 14 --inputs main_input:0 --outputs denoise_output/Sigmoid:0,vad_output/Sigmoid:0
```

TransposeOptimizerの処理が無限ループに陥るようなので、故意にエラーを発生させることで、エクスポートすることができた。
〇 tf2onnx/optimizer/transpose_optimizer.py
```
class TransposeOptimizer(GraphOptimizerBase):
    ...
    def _handle_nhwc_tranpose(self, trans):
         ...
```
↓
class TransposeOptimizer(GraphOptimizerBase):
    ...
    def _handle_nhwc_tranpose(self, trans):
        1/0
         ...
