### ISSUE TITLE
ADD Japanese-CLIP

### ISSUE THREAD

**Issue by itsmeterada** [axinc-ai/ailia-models#1246]
https://github.com/rinnakk/japanese-clip

**Comment by kyakuno** [comment]
@ooe1123 BARKが終わったら、こちらのモデルをお願いできればと考えています。

**Comment by kyakuno** [comment]
データセットはCC12M。
https://github.com/google-research-datasets/conceptual-12m

**Comment by kyakuno** [comment]
```
Training
The model was trained on [CC12M](https://github.com/google-research-datasets/conceptual-12m) translated the captions to Japanese.
```
https://huggingface.co/rinna/japanese-clip-vit-b-16

**Comment by kyakuno** [comment]
TokenizeにはT5Tokenizerを使用している。
