### ISSUE TITLE
Invalid color conversion in yolov3 sample

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#126]
OpenCV is normaly using BGR color format.
But yolov3 sample using 
  img = cv2.cvtColor(frame, cv2.COLOR_RGB2BGRA).
This code should be 
  img = cv2.cvtColor(frame, cv2.COLOR_BGR2BGRA).

**Comment by sngyo** [comment]
Sorry for my misunderstanding and thank you for the correction!
