### ISSUE TITLE
ADD hifi-gan

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1265]
https://github.com/jik876/hifi-gan
Fast MelSpectrum2Wave that also runs on CPU.

**Comment by kyakuno** [comment]
tacotron2のwaveglowを置き換えたい。

**Comment by kyakuno** [comment]
https://qiita.com/NoriakiOshita/items/02deaa9af5dbbca02add

**Comment by kyakuno** [comment]
1. Register as hifi gan on ailia-models as a single model.
2. Allow it to be specified as an option to tacotron2.
https://github.com/axinc-ai/ailia-models/tree/master/audio_processing/tacotron2

**Comment by YToleubay** [comment]
1. https://github.com/axinc-ai/ailia-models/pull/1288 it is for task 1, Register  hifi gan on ailia-models as a single model.
2.  https://github.com/axinc-ai/ailia-models/pull/1287 it is for task 2, Allow it to be specified as an option to tacotron2.

**Comment by kyakuno** [comment]
We have exported LJ_FT_T2_V1. I checked the paper, it was the model that provided the highest scores.
