### ISSUE TITLE
yolov3-face set_input_shape h-w order

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#128]
before: `set_input_shape(height, weight)`

correct: `set_input_shape(width, height)`

**Comment by sngyo** [comment]
他のモデルで呼び出さずに使用できているので削除してしまってもいいのか？それともほかが間違っているのか

**Comment by kyakuno** [comment]
detector apiの中でset input shapeが呼び出されるため呼び出し不要です。

**Comment by sngyo** [comment]
承知しました．ありがとうございます
