### ISSUE TITLE
ADD LCM

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1307]
https://github.com/luosiallen/latent-consistency-model

**Comment by kyakuno** [comment]
これに対してLCMは、ランダムノイズの状態から1ステップで画像を生成することで、劇的な高速化をはかっています。さらに2～4ステップを追加すれば、画像の品質も引き上げられます。Stable Diffusionのやり方だと、1ステップ目はまだノイズが多く残っている状態で、どのような画像が成立しようとしているのかわかりませんが、LCMでは1ステップだけで明確な画像が生み出されてくるわけです。
https://news.yahoo.co.jp/articles/05e8b6857fa21aa1e81cdd7c19fd5dee2744daf7

**Comment by YToleubay** [comment]
@kyakuno 
https://github.com/axinc-ai/ailia-models/tree/Latent-consistency-model-txt2img/diffusion/latent-consistency-models committed files, 
I have already changed download.sh and supported models list. 

Models are located here: https://drive.google.com/drive/folders/1XMKv9-yYrALC3jq3sDPUEgAJ9uDftirh?usp=sharing

I will be waiting for remote path

**Comment by kyakuno** [comment]
I uploaded models here.
https://storage.googleapis.com/ailia-models/latent-consistency-models/model.onnx_data
