### ISSUE TITLE
How to use on colab?

### ISSUE THREAD

**Issue by iminahiljaved** [axinc-ai/ailia-models#1374]
i have cloned the repo in colab , can anyone guide me through how to use it ?
p.s i want to use background removal

**Comment by itsmeterada** [comment]
You need to download the SDK and install it to your colab. (Also the license file will be sent to your email.)

Here is the guide:
https://github.com/axinc-ai/ailia-models/blob/master/TUTORIAL.md

**Comment by kyakuno** [comment]
@iminahiljaved I creaetd colab example.
https://github.com/axinc-ai/ailia-models/blob/master/hello_ailia.ipynb
