### ISSUE TITLE
yolox_s option to Mivolo

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1391]
mivoloで使用しているyolov8をyolox_s + retinafaceに置き換えられないか検討。選択可能なオプションを追加するイメージ。

**Comment by kyakuno** [comment]
yolov8が非常に重いので高速化したいのと、yolov8がGPLであることが気になるため。

**Comment by kyakuno** [comment]
デフォルトではyolov8で、オプションを指定するとyoloxにしたい。

**Comment by mucunwuxian** [comment]
@kyakuno
こちら、ありがとうございます！
了解しました。
対応させて頂こうと思います。

**Comment by mucunwuxian** [comment]
**📝 （備忘）**

- MiVOLOの[リポジトリ](https://github.com/WildChlamydia/MiVOLO)にて紹介されているLagendaというデータセットがダウンロードできた為、それを用いてyoloxの学習を実施します。
- `lagenda_annotation.csv` がannotationになりますが、35万弱行となります
- `lagenda_benchmark_images.zip` がimagesになりますが、50GB程のデータ量となります
- 独自のデータ形式ですので、私は一度yolov5の形式にマニュアルで変更した後、yolo2cocoというライブラリを用いて、yolox対応の学習データ形式であるcoco形式に変換をしました
- データ量が多い為、学習には時間を要しますが、データ品質が良い為、モデルはかなり高精度に仕上がります
