### ISSUE TITLE
whysperのlarge/large-v3モデルで長いファイルを変換すると途中からおかしくなる

### ISSUE THREAD

**Issue by itsmeterada** [axinc-ai/ailia-models#1393]
長めのファイルを変換しようとしたところ、途中から結果がおかしくなる現象がある。（同じ文章が繰り返し出力される）

テストに使用したファイル。
https://drive.google.com/file/d/1xXThyWwK_o0_gkKbtdULYwAzZqlE2c9M/view?usp=drive_link

結果
large-v3はCPU/GPUでも同様の結果。small/medium/largeでは発生しない。

[out_large-v3.txt](https://github.com/axinc-ai/ailia-models/files/14231917/out_large-v3.txt)
[out_large-v3_cpu.txt](https://github.com/axinc-ai/ailia-models/files/14231918/out_large-v3_cpu.txt)
[out_large.txt](https://github.com/axinc-ai/ailia-models/files/14231920/out_large.txt)

**Comment by itsmeterada** [comment]
largeとlarge-v3は同じコードで動いているが、雰囲気的には確保しているワーク用の領域が足りていないか、どこかの領域を壊していそう。

**Comment by kyakuno** [comment]
@ooe1123 きりのいいところでこちらのissueを確認いただけると嬉しいです。

**Comment by kyakuno** [comment]
whisper large v3はハレーションが発生しやすいという話はある。まずは公式のwhisper v3でbeam size=1にして挙動を確認すると良さそう。
https://deepgram.com/learn/whisper-v3-results

**Comment by kyakuno** [comment]
こちらのデータでもlarge-v3の評価が低いですね。
https://research.reazon.jp/blog/2024-02-14-ReazonSpeech.html

**Comment by ooe1123** [comment]
同じ文章が繰り返される症状と、入力ファイルの長さは関係がないようです。

audio_utils.pyにて、
flg_ffmpeg = True
と設定を変えると、（オリジナルwhisperと同じ方法）
02:27.660～の同じ文章が繰り返される症状は解消しました。
（ただし、04:55.180～から同様に同じ文章が繰り返される症状が発生します）

① wavファイルの読み込み (ffmpegからlibrosaに変更)
② log_mel_spectrogramの処理 (torchからlibrosaに変更)
③ melからaudio_featuresに変換 (torchからonnxに変更)
④ audio_featuresからlogitsを取得 (torchからonnxに変更)
⑤ logitsからtokenにデコード処理

whisperの処理はこのような流れになっていますが、
③、④のDNNのところでオリジナルと比較すると多少の誤差が出ていて、
①と②ではかなりの違いが出ていましたが、適切な結果が出ているようだったので
OKと判断していました。

結局、これらの誤差が積み重なった結果、致命的に間違った結果となってしまうことがあるのだと思います。

**Comment by kyakuno** [comment]
詳細な調査ありがとうございます！原因と対応方針、了解しました！

**Comment by kyakuno** [comment]
#1405 でwhisper公式に導入された、テキストのデコード結果をzlibで圧縮し、圧縮率が高すぎたら繰り返しと判定してfallbackする機能を導入しました。
