### ISSUE TITLE
ADD VOLO

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1394]
物体識別モデル
https://github.com/sail-sg/volo

**Comment by kyakuno** [comment]
優先度は低め。

**Comment by mucunwuxian** [comment]
@yuki399 
横から大変恐縮です。
VOLOの記事を執筆している関係で、当該issue、及び、PRを覗かせて頂いた次第です。
大江さんからの教示なのですが、fold処理とunfold処理を、自前実装するとopset11でもonnxエクスポートが実施できます。
ちょっと記載が荒いのですが、以下ご参考までに。
https://github.com/axinc-ai/ailia-models/issues/66#issuecomment-1826704290
