### ISSUE TITLE
ADD sdxl-turbo

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1435]
高速な画像生成モデル。
https://huggingface.co/stabilityai/sdxl-turbo

**Comment by kyakuno** [comment]
SDXLはnon-commercial-user-only。

**Comment by kyakuno** [comment]
ONNXは下記にあった。
https://huggingface.co/blog/sdxl_ort_inference

**Comment by ooe1123** [comment]
ONNXエクスポート

optimum-cli export onnx --model stabilityai/sdxl-turbo --task stable-diffusion-xl onnx/
