### ISSUE TITLE
ADD Council-GAN for Glasses removal

### ISSUE THREAD

**Issue by prolleytroblems** [axinc-ai/ailia-models#145]
https://github.com/Onr/Council-GAN

https://arxiv.org/pdf/1911.10538.pdf

**Comment by kyakuno** [comment]
TODO : Retrain glass removal gan with 256x256

**Comment by prolleytroblems** [comment]
I was unable to retrain on my machine, with 8GB V-RAM. Terada-san mentioned I may be able to use a machine with TITAN RTX, but has not yet gotten back to me since then.
https://axincai.slack.com/archives/CMNGUJ6TY/p1597066568055200

**Comment by prolleytroblems** [comment]
Finished, but not entirely successfully
