### ISSUE TITLE
questions about HRNet model, from pytorch to onnx

### ISSUE THREAD

**Issue by sakura-iv** [axinc-ai/ailia-models#148]
Hello, I am working on HRNet these days, and I am trying to export the initial pytorch model to onnx model. I mention that you have already exported the pytorch model to onnx model, I wanna ask how did you do that? I have met so many errors until now...

I wonder if it is convenient to you to release the export code to me? Many thanks !

**Comment by sngyo** [comment]
Hello, I accidentally deleted the original export code, so it may not be the same as the one I was using at the time, but I made sure I could export HRNet with the following code. Hope it works out for you!

1. checkout pytorch-v1.1 branch https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/pytorch-v1.1
2. download pre-trained model
3. make file `HRNet-Semantic-Segmentation/tools/torch2onnx.py` and paste the following code.
4. change ` STATE_FILE = "YOUR_MODEL.pth" ` to your downloaded pre-trained model path.
5. Run `torch2onnx.py`
```bash
$ cd HRNet-Semantic-Segmentaion
$ python3 tools/torch2onnx.py  --cfg experiments/cityscapes/<CHOOSE_CORRESPONDING_YAML_FILE>.yaml
```

---

```python3
import argparse
import os
import pprint
import shutil
import sys
import logging
import time
import timeit
from pathlib import Path

import numpy as np

import torch
import torch.nn as nn
import torch.backends.cudnn as cudnn

import _init_paths
import models
import datasets
from config import config
from config import update_config
from core.function import testval, test
from utils.modelsummary import get_model_summary
from utils.utils import create_logger, FullModel


def parse_args():
    parser = argparse.ArgumentParser(description='Train segmentation network')
    parser.add_argument('--cfg',
                        help='experiment configure file name',
                        required=True,
                        type=str)
    parser.add_argument('opts',
                        help="Modify config options using the command-line",
                        default=None,
                        nargs=argparse.REMAINDER)
    args = parser.parse_args()
    update_config(config, args)
    return args


def main():
    args = parse_args()

    # cudnn related setting
    cudnn.benchmark = config.CUDNN.BENCHMARK
    cudnn.deterministic = config.CUDNN.DETERMINISTIC
    cudnn.enabled = config.CUDNN.ENABLED

    # create model
    model = eval('models.'+config.MODEL.NAME + '.get_seg_model')(config)

    # load pre-trained weight
    # TODO make this an argument ?

    # ===== CHANGE HERE =================================== 
    STATE_FILE = "YOUR_MODEL.pth"
    # =====================================================

    pretrained_dict = torch.load(STATE_FILE)
    model_dict = model.state_dict()
    pretrained_dict = {
        k[6:]: v for k, v in pretrained_dict.items()
        if k[6:] in model_dict.keys()
    }
    model_dict.update(pretrained_dict)
    model.load_state_dict(model_dict)

    model = model.cuda()

    # evaluation mode
    model.eval()
    dummy_input = torch.autograd.Variable(torch.randn(
        (1, 3, 512, 1024)
    )).cuda()

    output = model(dummy_input)

    torch.onnx.export(
        model,
        dummy_input,
        'hrnet_w48_cityscapes_cls19_1024x2048_ohem_trainvalset.onnx',
        verbose=False,
        opset_version=10,
    )

    print(f'[DEBUG] output.shape: {output.shape}')


if __name__ == '__main__':
    main()

```

**Comment by sakura-iv** [comment]
Wow I really appreciate your help! My export code is very similar with yours, and I get the same error using your export code. It is so weird....
My pytorch version is 1.1 and all the other packages needed in this project are in the same version with requirement.

> Traceback (most recent call last):
>   File "tools/torch2onnx1.py", line 91, in <module>
>     main()
>   File "tools/torch2onnx1.py", line 84, in main
>     opset_version=10,
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
>     return utils.export(*args, **kwargs)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
>     strip_doc_string=strip_doc_string)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
>     _retain_param_name, do_constant_folding)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
>     _disable_torch_constant_prop=_disable_torch_constant_prop)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
>     graph = torch._C._jit_pass_onnx(graph, operator_export_type)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
>     return utils._run_symbolic_function(*args, **kwargs)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
>     return fn(g, *inputs, **attrs)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
>     args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
>     args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
>     raise RuntimeError("Failed to export an ONNX attribute, "
> **RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible**
> 

I think I have to ponder on it for more days.... Anyway, thanks a lot !

**Comment by sngyo** [comment]
I'm sorry that it did not work for you.
In my opinion, it looks more like a problem on pytorch's part. (ex. https://github.com/onnx/tutorials/issues/137)

I've had success with torch 1.5, please consider to update to the latest version and try it. 
When I tried it on torch 1.1, another error occurred in my environment and I was unable to export.

In addition, since our ailia is compatible with onnx opset10, the export is done with opset10, but Upsample/Resize recommends exporting with opset11, so please consider this as well.

**Comment by sakura-iv** [comment]
Ok, I will try some other methods. Really appreciate your help！！！！！！ (*^▽^*)
