### ISSUE TITLE
U2Net quality problem

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#153]
Right side quality is good, but left side quality seems bad. We need to investigation.

![debug_directry_u2net](https://user-images.githubusercontent.com/38881041/87779978-b52cfd80-c868-11ea-8bc6-366989616d4c.png)

https://github.com/NathanUA/U-2-Net/blob/master/figures/u2netqual.png

**Comment by kyakuno** [comment]
Same issue if we used ONNXRuntime.

**Comment by kyakuno** [comment]
Maybe caused by resize operator mismatch on opset=10.

```
 #/usr/local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:198: UserWarning: You are trying to export the model with onnx:Resize for ONNX opset version 10. This operator might cause results to not match the expected results by PyTorch.
 #ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
 #We recommend using opset 11 and above for models using this operator. 
```

But ONNXRuntime raise exceptions with model of opset=11.

```
#'Linear' mode and 'Cubic' mode only support 2-D inputs ('Bilinear', 'Bicubic') or 4-D inputs with the corresponding outermost 2 scale values being 1 in the Resize operator
```

**Comment by kyakuno** [comment]
https://github.com/microsoft/onnxruntime/issues/2463

**Comment by kyakuno** [comment]
I upgrade to torch 1.3.0 to 1.5.1, the exported problem with opset=11 was fixed. And I got good result.

![debug_directry_u2net](https://user-images.githubusercontent.com/38881041/87782854-43f04900-c86e-11ea-89c9-3f56de02ce52.png)

**Comment by kyakuno** [comment]
Converted model.
https://storage.googleapis.com/ailia-models/u2net/u2net_opset11.onnx
https://storage.googleapis.com/ailia-models/u2net/u2net_opset11.onnx.prototxt
https://storage.googleapis.com/ailia-models/u2net/u2netp_opset11.onnx
https://storage.googleapis.com/ailia-models/u2net/u2netp_opset11.onnx.prototxt

**Comment by kyakuno** [comment]
ailia SDK will support opset=11.

**Comment by pravinkhbari** [comment]
with c++ same issue with arch large and opset 10

**Comment by Onlybmachine** [comment]
> Converted model.
> https://storage.googleapis.com/ailia-models/u2net/u2net_opset11.onnx
> https://storage.googleapis.com/ailia-models/u2net/u2net_opset11.onnx.prototxt
> https://storage.googleapis.com/ailia-models/u2net/u2netp_opset11.onnx
> https://storage.googleapis.com/ailia-models/u2net/u2netp_opset11.onnx.prototxt

excuse me,  what is "--input_shape = "?

**Comment by kyakuno** [comment]
input shape is (1,3,320,320).

(2020-May-16) We fixed the upsampling issue of the network. Now, the model should be able to handle arbitrary input size. (Tips: This modification is to facilitate the retraining of U^2-Net on your own datasets. When using our pre-trained model on SOD datasets, please keep the input size as 320x320 to guarantee the performance.)
