### ISSUE TITLE
Model Licenses - could you please add some details

### ISSUE THREAD

**Issue by metal3d** [axinc-ai/ailia-models#1546]
Hello,

I'm creating a node to make human segmentation in ComfyUI - 3 models can help me from your repository (LIP, Pascal and ATR resnet).

I don't need the SDK, I simply use `onnxruntime` to make my inference code.

Your models are in a Google Drive, open to download. That works like a charm.

So, I wonder if:

- I can make my ComfyUI downloading your model from your drive
- I can, put them elsewhere, like HuggingFace (or maybe you already did it)

Of course, I will refer Ailla / AXincAI in the README if you allow me.

I can see an MIT license in the directory, including "all the files". I guess that I can use and redistribute the model, but I prefer asking before...

Thanks!

**Comment by kyakuno** [comment]
@metal3d Thank you for your inquiry.

You can download the ONNX models from our GCS directly and use them in your ComfyUI scripts. Feel free to also place them elsewhere. Please include a link to ailia-models' GitHub in your README if you do so.

Each ONNX model converted by us has a LICENSE file. Please include the original LICENSE file (included in each model folder of ailia-models) as needed.

**Comment by metal3d** [comment]
I'd like to thank you not only for this response, but also and above all for offering the free use of these models to the community. I'm a fervent advocate of open knowledge and the forces that enable solutions to evolve.

I am therefore deeply grateful to you.

**Comment by kyakuno** [comment]
Thank you for your appreciation. We are developing and providing our unique AI framework, ailia SDK, but we also aim to contribute to the open development of AI beyond that framework.
