### ISSUE TITLE
ADD pytorch-hair-segmentation SqueezeNet version

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#155]
Already exported resnet version. We want to export squeezenet version.

pspnet_squeezenet_sgd_lr_0.002_epoch_46_test_iou_0.882.pth
https://github.com/YBIGTA/pytorch-hair-segmentation/tree/master/models

**Comment by ooe1123** [comment]
onnxエクスポート時、以下のエラーが発生する。
```
RuntimeError: ONNX export failed: Couldn't export operator aten::adaptive_avg_pool2d
```

**Comment by kyakuno** [comment]
入力解像度を固定すれば標準のaveragepoolに置き換えられるかもしれません。

**Comment by kyakuno** [comment]
adaptive_avg_pool2dは，出力サイズを指定すると，自動的にカーネルサイズ等を決定してくれる
https://bibo6.hatenablog.jp/entry/2021/02/07/080710

**Comment by ooe1123** [comment]
入力サイズを可変にせず固定化した場合、エクスポートできそうでした。
resnet/squeezenetを適用した後に、サイズ=6のadaptive_avg_pool2dを適用するために、その入力テンソルのサイズが6の倍数になっている必要があって、pspnet_resnet101の場合は576、pspnet_squeezenetの場合は592くらいにするのがよさそうです。
（出力テンソルのサイズが、resnetの場合は入力サイズの1/16、squeezenetの場合は1/16-1となるもよう）
