### ISSUE TITLE
ADD BeautyGAN

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#161]
https://github.com/wtjiang98/BeautyGAN_pytorch

**Comment by kyakuno** [comment]
I could not find pre-trained model.
There are some model of tensorflow version.
But no license.
https://github.com/Honlan/BeautyGAN

**Comment by ooe1123** [comment]
http://colalab.org/projects/BeautyGAN
こちらからダウンロードできるデータセットにはサンプルコード内で参照している train_***.txt, test_***.txt が含まれていない。
https://github.com/wtjiang98/BeautyGAN_pytorch/issues/1#issuecomment-622409620 こちらを参考にして作成する。

**Comment by ooe1123** [comment]
https://github.com/wtjiang98/BeautyGAN_pytorch/issues/1#issuecomment-544877132
こちらのリンクから vgg_conv.pth をダウンロードし、addings/vgg_conv.pth に配置する。

**Comment by ooe1123** [comment]
solver_makeup.py の class Solver_makeupGAN の def vis_test() で、学習中のtestデータセットに対する推論結果の出力を行っているが、組み合わせにより大量の推論を行い実行に時間がかかるため、適当な量で打ち切るようにする。
```
    def vis_test(self):
        ...
        for i, (img_A, img_B) in enumerate(self.data_loader_test):
            ...
            
            if 1000 <= i:
                break
```

呼び出し頻度も抑止するようにする。
```
    def train(self):
        ...
        for self.e in range(start, self.num_epochs):
            ...

            if self.e+1 % 10 == 0:
                print("Saving output...")
                self.vis_test()
```
