### ISSUE TITLE
Modify LivePortrait facemsh

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#1610]
LivePortraitのfacemeshモードだと、出力が揺らぐ（顔のキーポイントが毎フレームずれるため？）問題を解消したい。
FasterLivePortraitも参照。
https://github.com/warmshao/FasterLivePortrait

**Comment by kyakuno** [comment]
@ooe1123 急ぎではないのですが、時間ができた時に検討いただけると嬉しいです。

**Comment by ooe1123** [comment]
@kyakuno 
揺らぎが気になるのは、サンプル画像でしょうか？ほかに気になるサンプル動画があればご提供いただければと思います。

insightfaceとfacemeshのキーポイント間には互換性がないと考えており、
代替のfacemeshからinsightfaceのキーポイントへの変換は、目検で判定して作った適当な変換式で行っています。

これを完全一致させるのは困難だと思っているのですが、
よいアイデアがありましたらご助言いただけると幸いです。

**Comment by kyakuno** [comment]
@ooe1123 すみません、スクリプトの問題ではなく、FP16の精度の問題のようでした。下記のコマンドでの実行結果となります。

```
python live_portrait.py --det facemesh
```

default FP32

https://github.com/user-attachments/assets/a2a64a16-c829-4b88-9501-9e226e909446

default FP16

https://github.com/user-attachments/assets/557e81f7-e35d-42e1-a50b-16a224231111

facemesh FP32

https://github.com/user-attachments/assets/b0893cae-31cc-4fb1-bf80-b91f73fbf8f3

facemesh FP16

https://github.com/user-attachments/assets/8f9eac2e-74ad-4b86-a24d-6d00715a1c8e

**Comment by ooe1123** [comment]
承知です。こちらクローズで大丈夫でしょうか？

**Comment by kyakuno** [comment]
はい、クローズさせていただきます。
