### ISSUE TITLE
ADD ST-GCN

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#167]
Skelton based action recognition (BSD)
https://github.com/zhujiagang/st-gcn-data-len

**Comment by kyakuno** [comment]
Example of st-gcn
https://github.com/yysijie/st-gcn/blob/master/OLD_README.md

**Comment by kyakuno** [comment]
```
        # pose estimation
        video, data_numpy = self.pose_estimation()

        # action recognition
        data = torch.from_numpy(data_numpy)
        data = data.unsqueeze(0)
        data = data.float().to(self.dev).detach()  # (1, channel, frame, joint, person)

        # model predict
        voting_label_name, video_label_name, output, intensity = self.predict(data)
```

https://github.com/yysijie/st-gcn/blob/master/processor/demo_offline.py

**Comment by kyakuno** [comment]
こちらだと、モデルフォーマットが(N, C, T, V, M)で5次元になっている見たい。
https://github.com/zhujiagang/st-gcn-data-len

こっちの方が良さそう。
https://github.com/yysijie/st-gcn

**Comment by kyakuno** [comment]
einsumはopset=12なので下記のスクリプトで対応できる模様
https://github.com/open-mmlab/mmskeleton/issues/202

**Comment by kyakuno** [comment]
変換スクリプト

```
    def pose_estimation(self):
        self.model.eval()
        from torch.autograd import Variable
        x = Variable(torch.randn(1, 3, 300, 18, 2))    # (1, channel, frame, joint, person)
        torch.onnx.export(self.model, x, 'st-gcn_pytorch.onnx', verbose=True, opset_version=10)
```

変換実行

```
python3 main.py demo_offline --use_gpu=False
```

st_gcn.pyの下記で定数じゃないと怒られる

```
        x = F.avg_pool2d(x, x.size()[2:])
        #RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
```

下記に置き換えるとexportはできる

```
x = F.avg_pool2d(x, (75,18))
```

**Comment by kyakuno** [comment]
怪しげなonnxはできたが動くかは不明。まずはPytorch上で動作を確認した方が良さそう。

[st-gcn_pytorch.onnx.zip](https://github.com/axinc-ai/ailia-models/files/5082612/st-gcn_pytorch.onnx.zip)

**Comment by kyakuno** [comment]
1.  下記のリポジトリをfork
https://github.com/yysijie/st-gcn
2. OpenPoseがcaffeが必要で動かないのでailiaのPoseEstimatorに置き換え 
3. リポジトリ上でst-gcnのeinsumを置き換えて動作確認
4. リポジトリ上でonnxruntimeで動作確認
5. ailiaのOpenPoseを使ってサンプルを作る

**Comment by kyakuno** [comment]
@tomo99nori 上記の手順で進めてみていただければと思います。

**Comment by ooe1123** [comment]
pyopenposeのインストール手順（for colaboratory）
1. 依存ライブラリのインストール
```
!apt-get -q install -y libatlas-base-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev protobuf-compiler libgflags-dev libgoogle-glog-dev liblmdb-dev opencl-headers ocl-icd-opencl-dev libviennacl-dev
!apt-get -q -y install swig
```
2. 特定のバージョンのcmakeをインストール
```
!wget -q https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
!tar xfz cmake-3.13.0-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local
```
3. `-DBUILD_PYTHON=1`オプション付きでビルド
```
!cd openpose && rm -rf build || true && mkdir build && cd build && cmake -DBUILD_PYTHON=1 .. && make -j`nproc`
```
4. インストール
```
!cd openpose/build && make install
```
モジュールが /usr/local/python/openpose にインストールされる。
