### ISSUE TITLE
ADD Clothing Detection

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#185]
https://github.com/simaiden/Clothing-Detection

**Comment by kyakuno** [comment]
labels
https://github.com/simaiden/Clothing-Detection/blob/master/yolo/df2cfg/df2.names
short sleeve top
long sleeve top
short sleeve outwear
long sleeve outwear
vest
sling
shorts
trousers
skirt
short sleeve dress
long sleeve dress
vest dress
sling dress

**Comment by kyakuno** [comment]
YOLOv3バージョンのエクスポートをお願いできればと思います。

**Comment by kyakuno** [comment]
labels
https://github.com/simaiden/Clothing-Detection/blob/master/yolo/modanetcfg/modanet.names
bag
belt
boots
footwear
outer
dress
sunglasses
pants
top
shorts
skirt
headwear
scarf/tie

**Comment by kyakuno** [comment]
df2とmodanetの両方のエクスポートをお願いします。

**Comment by ooe1123** [comment]
maskrcnn-benchmarkのビルドは以下の環境で行う必要がある。
* torch==1.4.0
* torchvision==0.5.0
[参考]
https://github.com/facebookresearch/maskrcnn-benchmark/issues/1236

**Comment by kyakuno** [comment]
yolov3のdarknetモデルの変換は、darknet -> keras-yolov3 -> onnxという手順になります。
https://medium.com/axinc/yolov3-66c9b998c096

**Comment by ooe1123** [comment]
faster、retinanet、maskrcnnモデルを使うには、maskrcnn-benchmark/maskrcnn_benchmark/config/defautl.pyにてNUM_CLASSES=14とする。
[参考]
https://github.com/simaiden/Clothing-Detection/issues/5
