### ISSUE TITLE
ADD tf fashion ai

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#186]
https://github.com/HiKapok/tf.fashionAI

**Comment by ooe1123** [comment]
学習済みのモデルを公開していないため、モデルの学習から行う必要がある？
https://github.com/HiKapok/tf.fashionAI/issues/9

**Comment by ooe1123** [comment]
学習データが公開終了しているため、ドキュメント通りの手順で学習ができない。
https://github.com/HiKapok/tf.fashionAI/issues/7

Alibaba cloudにアカウントを作って、こちらから類似の学習データをダウンロードできるっぽい。
https://tianchi.aliyun.com/museum7/?spm=5176.14046517.J_9711814210.23.2bd17c0aFQzXFg#/newprodetail?productId=7

**Comment by ooe1123** [comment]
モデルの学習から試してみるが、エラーで実行できなかった。

① fashionAI_keypoints_train*.tarをもとに、convert_tfrecords.pyを使って *.tfrecord を作成する。
（config.RECORDS_DATA_DIRを使った処理がコメントアウトされているので、コメントインする）

② train_senet_cpn_onebyone.py を実行
エラーが発生
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, 1-th value returned by pyfunc_0 is int32, but expects int64
	 [[Node: vgg_distort_image/map/while/PyFunc = PyFunc[Tin=[DT_INT64, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_INT64], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](vgg_distort_image/map/while/TensorArrayReadV3, vgg_distort_image/map/while/PyFunc/input_1, vgg_distort_image/map/while/PyFunc/input_2)]]
```

**Comment by ooe1123** [comment]
FashionAI の別のモデル
https://github.com/gathierry/FashionAI-KeyPointsDetectionOfApparel
