### ISSUE TITLE
ADD human part segmentation

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#199]
Search some model

**Comment by kyakuno** [comment]
https://github.com/mayankgrwl97/human-part-segmentation

**Comment by kyakuno** [comment]
MIT
https://github.com/PeikeLi/Self-Correction-Human-Parsing

**Comment by ooe1123** [comment]
エクスポートエラー対応
① RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::PythonOp
　modules/functions.pyのInPlaceABNSync.forward()が return x, running_mean, running_var でリストを返しているが、xしか使わないので修正
② RuntimeError: ONNX export failed: Couldn't export Python operator InPlaceABNSync
　modules/functions.pyのclass InPlaceABNSync が nn.Moduleではなくautograd.Functionを継承して作られているため、エクスポートに対応していない？
　実装内容をmodules/bn.pyのInPlaceABNSync.forward() に移植する。
③ RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d
　opset_version=10の場合発生する。opset_version=11だとOK

**Comment by ooe1123** [comment]
④ torch.utils.cpp_extension を使用していると、正しくエクスポートできないもよう。
　modules/bn.pyのInPlaceABNSync.forward() でpytorch実装を使うようにする。

　[修正後]
```
class InPlaceABNSync(ABN):
    def forward(self, x):
        x = super().forward(x)
        return x
```
