### ISSUE TITLE
ADD GAST NET

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#246]
https://github.com/fabro66/GAST-Net-3DPoseEstimation

**Comment by kyakuno** [comment]
MIT

**Comment by ooe1123** [comment]
以下を修正することで、サンプルコードを実行できた。
○ tools/visualization.py
```
ax.set_aspect('equal')
```
↓
```
ax.set_aspect('auto')
```

また、matplotlib==3.1.0 のバージョンをインストールする。

[参考]
https://github.com/fabro66/GAST-Net-3DPoseEstimation/issues/16

**Comment by ooe1123** [comment]
torch1.7だと、エクスポート時以下のエラーが発生する
```
RuntimeError: Input, output and indices must be on the current device
```

torch1.4だと、以下のエラーが発生するが、
```
/home/ooe/env_torch1.4/lib/python3.7/site-packages/torch/onnx/utils.py:655: UserWarning: ONNX export failed on ATen operator eye because torch.onnx.symbolic_opset11.eye does not exist

  File "/home/ooe/env_torch1.4/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'eye'
```
model/local_attention.py の以下のコードを修正することでtorch1.4でエクスポートできた。
```
E = torch.eye(adj.size(1), dtype=torch.float).to(input.device)
```
↓
```
E = torch.eye(17, dtype=torch.float).to(input.device)
```
※ 17の値は、num-jointsの指定による
※ RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results). のワーニングがでるが、固定値で問題なさそう

**Comment by ooe1123** [comment]
上記でエクスポートしたモデルはonnxruntimeでもロード時にエラーが発生する。(ATen index_putのエラー)

エラーの原因となっていそうな箇所を以下のように置き換え
○ reconstruction.py の def reconstruction()内のモデルロード直後に_adjを計算するように修正
```
    model_pos.load_state_dict(checkpoint['model_pos'])
    for conv in model_pos.layers_graph_conv:
        for x in (conv.local_graph_layer.gcn_sym, conv.local_graph_layer.gcn_con,):
            x._adj = -9e15 * torch.ones_like(x.adj)
            x._adj = x._adj.to(x.e.device)
            x._adj[x.m] = x.e.view(-1)
            x._adj = x._adj.detach()
```
○ model/local_attention.py の SemCHGraphConv.forward() を以下のように修正
```
        adj = -9e15 * torch.ones_like(self.adj, dtype=torch.float).to(input.device)  # C * J * J
        adj[self.m] = self.e.view(-1)
        adj = F.softmax(adj, dim=2)
```
↓
```
        adj = F.softmax(self._adj.to(input.device), dim=2)
```
