### ISSUE TITLE
ADD flownet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#257]
https://github.com/NVIDIA/flownet2-pytorch
apache

**Comment by kyakuno** [comment]
CUDAがないとエクスポートできない感がある。

**Comment by kyakuno** [comment]
Resample2DはCUDAのModuleになっている。
https://github.com/NVIDIA/flownet2-pytorch/tree/master/networks/resample2d_package

**Comment by kyakuno** [comment]
Pytorch moduleが使えるかも
https://github.com/wanghao9610/flownet2-pytorch-module

**Comment by kyakuno** [comment]
cuda moduleが必要なのは変わらないみたい

**Comment by mucunwuxian** [comment]
@kyakuno 
現在の作業が諸々落ち着いた後、こちらを担当させて頂いてもよろしいでしょうか？
難しさについては、上記コメント等を参考にさせて頂こうと思います。

或いは、大変恐縮ながら、[flownet2](https://github.com/NVIDIA/flownet2-pytorch)のonnx化がどうしても難しい場合には、その前身と言えるシンプル構造の[flownet](https://github.com/ClementPinard/FlowNetPytorch)もあるようでして、技術実現としては代替となり得るかもしれないと思いました。
（あくまで参考までにのコメントとなります。🙇）

**Comment by kyakuno** [comment]
了解しました！よろしくお願いします。

**Comment by mucunwuxian** [comment]
@kyakuno 
ありがとうございます！🙇

**Comment by mucunwuxian** [comment]
# Optical Flow Estimationについての調査結果まとめ 📝

Optical Flowを推定する最新技術についてリサーチを行った結果を、冗長ながらまとめさせて頂きます。

<br/>

## 1. 技術の大まかな歴史

とても良いsurvey論文がありましたので、そちらを参考にさせて頂きました。
特に、教師ありのDeep Learningベースに手法に関する記述を、追いかけました。
file:///Users/mucunwuxian/Downloads/1-s2.0-S0031320321000480-main-online.pdf

<br/>
<br/>

教師ありのDeep Learningベースの手法で言うと、以下の手法などが有名であるようです。

![image](https://user-images.githubusercontent.com/9916906/126604276-102774c1-744e-4615-a3ff-6ce1a12e6341.png)

<br/>
<br/>

年表一番左に記載されるのが、2015年頃に発表されたFlowNetになります。
[FlowNetの論文](https://arxiv.org/pdf/1504.06852.pdf)に記載される、抽象的な概念図が、幾つかの論文にてリファーされている、基本的な処理概念となっているようです。
前後2frameを入力として、その間に生じるOptical Flowを推定する形です。

![image](https://user-images.githubusercontent.com/9916906/126606960-b42b017e-6100-482c-88d4-2d34437e3d6e.png)

<br/>
<br/>

尚、FlowNetにおけるEncorder・Decorderの構造は、以下のようなシンプルな形状でした。
尚、FlowNetSと、FlowNetCは、Encorderが異なり、Decorderは共通になります。

![image](https://user-images.githubusercontent.com/9916906/126607316-f8503b40-ea64-47b6-8a6b-993bc6a1a931.png)
![image](https://user-images.githubusercontent.com/9916906/126654155-3ce1e3be-36a6-40d1-a3ca-6c976af41712.png)

<br/>
<br/>

そして、このFlowNetの精度を大幅改善したのが、2017年頃に発表されたFlowNet2.0となります。
構造は[FlowNet2.0の論文](https://arxiv.org/pdf/1612.01925.pdf)に記載されている、以下の複雑な構造となっています。

![image](https://user-images.githubusercontent.com/9916906/126636787-a31f6e2d-4f1d-448a-808f-6c32cfb31889.png)

<br/>
<br/>

その後、PWC-Netや、SelFlowなどと呼ばれる手法が出てきたようで、2019年頃迄に徐々に精度が改善されていったようです。
昨今ですと、SOTAに並ぶラインナップとしては、MaskFlownet、RAFT、GMAといった手法が並んでいるようです。
精度を表にまとめると、以下の関係となっています。
比較対象として分かりやすいように、FlowNet2.0も並べて表示します。

![image](https://user-images.githubusercontent.com/9916906/126653760-a77fa513-d147-4352-8fae-28769195ed7b.png)

<br/>
<br/>

MaskFlownetは、

オクルージョンマスクを学習できる非対称機能マッチングモジュールを提案

![image](https://user-images.githubusercontent.com/9916906/126655183-b936b738-4729-415e-8d74-41d5e109ef8e.png)
