### ISSUE TITLE
ADD vit

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#275]
https://github.com/lucidrains/vit-pytorch

**Comment by mucunwuxian** [comment]
# リサーチ備忘📝

調査した結果につきまして、こちらに記載させて頂こうと思います。

<br/>

## 「lucidrains/vit-pytorh」について

[pytorch版のvitリポジトリ](https://github.com/lucidrains/vit-pytorch)について、確認させていただきました。
通常のvitだけでなく、複数種類のvitも登録されており、素晴らしいリポジトリとなっています。

Licenseは、MITになります。

リポジトリの構成としては、以下のようになっています。
```
./
├── LICENSE
├── README.md
├── examples
│   └── cats_and_dogs.ipynb
├── images
│   ├── cait.png
│   ├── cross_vit.png
│   ├── cvt.png
│   ├── dino.png
│   ├── distill.png
│   ├── levit.png
│   ├── nest.png
│   ├── pit.png
│   ├── t2t.png
│   ├── twins_svt.png
│   └── vit.gif
├── setup.py
└── vit_pytorch
    ├── __init__.py
    ├── cait.py
    ├── cross_vit.py
    ├── cvt.py
    ├── deepvit.py
    ├── dino.py
    ├── distill.py
    ├── efficient.py
    ├── levit.py
    ├── local_vit.py
    ├── mpp.py
    ├── nest.py
    ├── pit.py
    ├── recorder.py
    ├── rvt.py
    ├── t2t.py
    ├── twins_svt.py
    └── vit.py
```

`images` フォルダに格納されている画像は、readmeの説明に用いられているものとなります。

`vit_pytorch` フォルダに格納されているモジュールは、各種vitネットワーク構造のdefや、その補助機能等になります。

`example` フォルダに格納されている `cats_and_dogs.ipynb` というファイルは、当該リポジトリのコードを用いてスクラッチで学習する方法をレクチャーしているものでした。
Kaggleにある `Dogs vs. Cats Redux: Kernels Edition` というデータセットにて、学習する例が実装してあります。

<br/>

readmeを読んでいくと、pre-trainedモデルのリンク紹介があった為、覗いてみると以下の別リポジトリへと繋がりました。

![image](https://user-images.githubusercontent.com/9916906/121093835-9640ac80-c828-11eb-8eae-61c03f0d00f2.png)
↓
https://github.com/rwightman/pytorch-image-models

しかし、当該リポジトリとリンク先リポジトリとを読み込んでみると、どうもvitそのもののpretrainedパラメーターは無さそうでした。
resnet等の有名なネットワークを、特徴抽出として用いるvitの場合に、その特徴抽出部分について、pretrainedモデルを用いれるというニュアンスのようでした。
或いは、readmeに記載のある学習サンプルにおいては、torchvisionのpretrainedモデルを用いて、蒸留を行う手順が記載されていたりしました。
https://github.com/lucidrains/vit-pytorch#distillation

<br/>

その為、一旦ではありますが、ailia上で動かすonnxの生成元として、このリポジトリは不十分である印象を受けました。
他のリポジトリについても、調査をしてみようと思います。

<br/>
<br/>

## 「jeonsworld/ViT-pytorh」について

以下のpytorch版のvitリポジトリ](https://github.com/lucidrains/vit-pytorch)について、確認させていただきました。
こちらも☆の数が600を超えるリポジトリで、中身も充実したものでした。

Licenseは、MITになります。

リポジトリの構成としては、以下のようになっています。
```
./
├── LICENSE
├── README.md
├── img
│   ├── figure1.png
│   ├── figure2.png
│   └── figure3.png
├── models
│   ├── configs.py
│   ├── modeling.py
│   └── modeling_resnet.py
├── requirements.txt
├── train.py
├── utils
│   ├── data_utils.py
│   ├── dist_util.py
│   └── scheduler.py
└── visualize_attention_map.ipynb
```

<br/>

`img` フォルダに格納されている画像は、readmeの説明に用いられているものとなります。

`models` フォルダに格納されているモジュールは、各種vitネットワーク構造のdefや、そのcofig補助機能等になります。

`utils` フォルダに格納されているモジュールは、学習の際に使用するloaderやscheduler等のdefとなります。

`visualize_attention_map.ipynb` というファイルは、当該リポジトリのコードを用いて、学習済みモデルにてfeed forwardを行うnotebook形式のチュートリアルとなっています。
学習済みモデルのダウンロードについても、コードでの実施が行われるように実装がされています。
また、attention mapによる、注目領域の可視化も行ってくれます。

![image](https://github.com/jeonsworld/ViT-pytorch/raw/main/img/figure3.png)

<br/>

結果も見せ方も良いコードとなっているので、こちらの踏襲すれば良いかと思ったのですが、よくよく調べてみると、このリポジトリにおけるモデルの実装は、`Vision Transformer` ではなく、`Compact Convolutional Transformer` というもののようでした。
その為、ひょっとすると、踏襲させていただくのは微妙かもしれないと思いました。

<br/>

尚、補足としまして、当該リポジトリを用いた学習については、事前学習済みモデルを用いて学習する方針が推奨されておりますが、逆にスクラッチでの学習を行おうとした場合には、一部コードの改変を要するようでありました。
https://github.com/jeonsworld/ViT-pytorch/issues/7

その為、スクラッチで学習をする場合には、[lucidrains/vit-pytorch](https://github.com/lucidrains/vit-pytorch)の方が適しているかもしれません。

<br/>
<br/>

## 「google-research/vision_transformer 」について

[lucidrains/vit-pytorch](https://github.com/lucidrains/vit-pytorch)のリポジトリを見ていると、officialリポジトリが以下である、という記載がありました。
https://github.com/google-research/vision_transformer

Licenseは、Apache-2.0になります。

google-researchによるJAXの実装になります。
notebookによる実装もあり、Colab上にてTPUを使いながら、学習から推論までを一通り実行することができました。
可視化についても、論文の方針と合致しています。

<br/>

（jax2onnxや、jax2pytorchの方法について、現在調査中になります…。）

<br/>

**Comment by mucunwuxian** [comment]
# リサーチ備忘２📝

先程までのリサーチを経て、概ねonnxエクスポートの方針は決まったのですが、ここで1つ想定外の事象が確認されました。
それは、[google-research/vision_transformer](https://github.com/google-research/vision_transformer)にて、実装されているvitが論文の図の通りではなく、compact convolutional transformerのような実装であることです。

具体的には、画像パッチの作成方法を、ストライドの広いconvolutionで行っています。
バラバラになった画像のパッチを可視化すると、デモとして面白いと思ったのですが、それが叶わない次第です。

<br/>

論文に記載されているネットワーク構造は以下です。

**論文の図（リポジトリのreadmeにもこの図が載っている）**
![image](https://user-images.githubusercontent.com/9916906/121264315-ecc5ed80-c8f1-11eb-9e39-a3890a0097fa.png)

<br/>

一方で、実際に実装されているネットワーク構造は、こちらに近いものです。

**compact convolutional transformer**
![image](https://user-images.githubusercontent.com/9916906/121264415-0d8e4300-c8f2-11eb-82cf-f21a2040086a.png)

↓

**（作られるパッチ画像768枚の内の1枚、pixabayの画像にて）**
![image](https://user-images.githubusercontent.com/9916906/121266367-5abfe400-c8f5-11eb-9d4d-672757889e22.png)

<br/>

このことに関連する質問のようなものが、リポジトリのissueにもありました。
（真意は掴みづらいのですが…。）
https://github.com/google-research/vision_transformer/issues/93

また、google-researchオリジナルのvitリポジトリ内を、rearrangeで検索しても検出がされませんでした。

<br/>

実際に、compact convolutional transformerのような実装がされてる該当コード部分は、以下となります。
https://github.com/google-research/vision_transformer/blob/96b6a636902eddab9ce93fdfe05eaa8b3997210e/vit_jax/models.py#L197

**（233行目）**
```
    n, h, w, c = x.shape

    # We can merge s2d+emb into a single conv; it's the same.
    x = nn.Conv(
        x,
        hidden_size, patches.size,
        strides=patches.size,
        padding='VALID',
        name='embedding')

    # Here, x is a grid of embeddings.
```

`# We can merge s2d+emb into a single conv; it's the same.`と、コメントにも意図がしっかり記載されています。

<br/>

これらの調査結果から、リポジトリの踏襲を行うという観点においては、compact convolutional transformerのような実装がされたモデルを、onnxエクスポートすることが順当かと思われました。

<br/>
<br/>

尚、論文に記載されるような画像をバラバラにして、パッチを得る方針しては、このissueのstart地点でもある[lucidrains/vit-pytorch](https://github.com/lucidrains/vit-pytorch)にて行われているようでした。

該当コードは以下です。
https://github.com/lucidrains/vit-pytorch/blob/60ad4e266ecf1df52968934f571dfe6acd736035/vit_pytorch/vit.py#L81

**（93行目）**
```
        self.to_patch_embedding = nn.Sequential(
            Rearrange('b c (h p1) (w p2) -> b (h w) (p1 p2 c)', p1 = patch_height, p2 = patch_width),
            nn.Linear(patch_dim, dim),
        )
```

これが論文の通りの実装かと思われます。
ただし、このリポジトリには、学習済みモデルが用意されていない為、この論文に則ったネットワーク構造にて、推論を実施することが難しい状況です。
実施するとすれば、imagenetで学習を実施する必要があります。

<br/>
<br/>

尚、attention mapについて実装をしているのが、[jeonsworld/ViT-pytorch](https://github.com/jeonsworld/ViT-pytorch)になります。

以下のような結果を、サンプルスクリプトから得ることができます。
![image](https://user-images.githubusercontent.com/9916906/121266925-547e3780-c8f6-11eb-9c57-89414886597b.png)

また、改めて見てみると、こちらのリポジトリで用いられている重みについても、GoogleのOfficialと書かれています。
恐らく、google-researchのvision_transformerから移植したという意味かと思われます。
![image](https://user-images.githubusercontent.com/9916906/121267154-b6d73800-c8f6-11eb-9969-90774a646064.png)

<br/>

尚、保存されている重みの形式が、`.npz`となっているのですが、これは[lukemelas/PyTorch-Pretrained-ViT](https://github.com/lukemelas/PyTorch-Pretrained-ViT)での保存形式と合致します。
恐らく、同様の移植をしたものと思われます。

<br/>

ただし、[jeonsworld/ViT-pytorch](https://github.com/jeonsworld/ViT-pytorch)については、若干オリジナルのロジックが加えられているような旨が、リポジトリのissueにて伺えます。
この点は、或いは、学習についてのみかもしれません。
予測精度について、大きなズレは無さそうな印象です。

**Comment by mucunwuxian** [comment]
### （tips）

**(patch images)**
![image](https://user-images.githubusercontent.com/9916906/122474597-6cdd0900-cffe-11eb-9c0b-21200c9ede04.png)
