### ISSUE TITLE
Reduce dependencies (requirements.txt)

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#282]
依存関係が多くなっているので、削減のためのリファクタリングを行う。
https://github.com/axinc-ai/ailia-models/blob/master/requirements.txt

**Comment by kyakuno** [comment]
certifi==2020.4.5.1 -> importされてない
chardet==3.0.4 -> importされてない
click==7.1.2 -> importされてない
cycler==0.10.0 -> importされてない
decorator==4.4.2 -> importされてない
filelock==3.0.12 -> importされてない
idna==2.9 -> importされてない
imagecodecs==2020.2.18 ->  importされてない
imageio==2.8.0 -> importされてない
joblib==0.14.1 -> importされてない
kiwisolver==1.2.0 -> importされてない
matplotlib==3.2.1 -> 各所で使われている
networkx==2.4 ->  importされてない
numpy==1.18.4 -> 各所で使われている
opencv-python==4.4.0.42 -> 各所で使われている
pillow==7.1.2 -> 各所で使われている
pyparsing==2.4.7 -> importされてない
python-dateutil==2.8.1 -> importされてない
pywavelets==1.1.1 -> importされてない
regex==2020.5.13 -> importされてない
requests==2.23.0 -> 各所で使われている
sacremoses==0.0.43 -> importされてない
scikit-image==0.17.2 -> skimage -> ilnet、prnet
scipy==1.4.1 -> deepsort、prnet
sentencepiece==0.1.90 -> importされてない
six==1.14.0 -> importされてない
tifffile==2020.5.11 -> importされてない
tokenizers==0.7.0 ->  importされてない、transformersが参照
tqdm==4.46.0 -> importされてない
transformers==2.9.1 -> nlpで使われている
urllib3==1.25.9 -> importされてない

**Comment by kyakuno** [comment]
Dependency Graph
https://github.com/axinc-ai/ailia-models/network/dependencies

**Comment by kyakuno** [comment]
[必須]
numpy==1.18.4
matplotlib==3.2.1
opencv-python==4.4.0.42
pillow==7.1.2
scipy==1.4.1
urllib3==1.25.9

[コード修正して依存削除]
scikit-image==0.17.2

[NLPだけで使う]
sentencepiece==0.1.90
tokenizers==0.7.0
transformers==2.9.1
sacremoses==0.0.43

[依存削除]
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
cycler==0.10.0
decorator==4.4.2
filelock==3.0.12
idna==2.9
imagecodecs==2020.2.18
imageio==2.8.0
joblib==0.14.1
kiwisolver==1.2.0
networkx==2.4
pyparsing==2.4.7
python-dateutil==2.8.1
pywavelets==1.1.1
regex==2020.5.13
requests==2.23.0
six==1.14.0
tifffile==2020.5.11
tqdm==4.46.0

**Comment by kyakuno** [comment]
@sngyo 上記の方針で気になるところはありますでしょうか。

**Comment by kyakuno** [comment]
ilnetからskimageを除去するのは、mean_bilateralとmorphologyがopencvにないので難しそう。

**Comment by sngyo** [comment]
@kyakuno ざっと確認しただけですが，問題なさそうです．
エラーが発生するようであれば都度修正するといった形で，問題ないと思います

**Comment by kyakuno** [comment]
確認ありがとうございます。では、上記の方針で整理します。

**Comment by kyakuno** [comment]
削減しました。
https://github.com/axinc-ai/ailia-models/commit/187647f356ca52440f43c744bd8cf5df691093d9
