### ISSUE TITLE
ADD multiview human pose

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#294]
https://github.com/microsoft/multiview-human-pose-estimation-pytorch
MIT

**Comment by hattan1990** [comment]
1.公式データセット（MPII+H36M）をMPIIデータのみに変更
　ダウンロードする際のアカウント登録が学術研究機関などのドメインに制限されており、H36Mデータの取得が困難なため
　※精度改善が必要な場合、H36Mデータの取得について要検討

2.MPIIデータを用いて、学習を実施（パラメータ：256_nofusion.yaml）
　python run/pose2d/train.py --cfg experiments-local/mpii/mobilenetv2/256_nofusion.yaml
　※backboneモデルは、mobilenetv2を使用

3.モデル検証を実施して、3D推論に必要な「predicted_heatmaps.h5」を取得
　python run/pose2d/valid.py --cfg experiments-local/mpii/mobilenetv2/256_nofusion.yaml

**Comment by hattan1990** [comment]
補足：「predicted_heatmaps.h5」は、modelの推論から生成可能なため、h5ファイルとして保存する必要はない

**Comment by kyakuno** [comment]
学習済みモデルが非公開で、精度の課題が解消しないため、一度、キャンセルします。
