### ISSUE TITLE
ADD paddle ocr

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#310]
https://github.com/PaddlePaddle/PaddleOCR
japanese crnn model

**Comment by mucunwuxian** [comment]
（以下、備忘となります…。📝）

<br/>

# 初期リサーチ結果

## 論文概要

  - Baiduによる軽量OCR、CRNN等による実現です
  - 速度と容量と精度のバランスに、多大な配慮を行っています
  - アルゴリズムの新規制よりは、実用に向けた調整方法を共有してくれるもので、地に足ついた非常に素晴らしい内容となっています
  - ［①文字位置検出］→［②文字向き認識／補正］→［③内容認識］という手順になります
    ![image](https://user-images.githubusercontent.com/9916906/104152903-41893900-5424-11eb-8250-b645316d4851.png)
  - 以下テクニックを導入されています
      - CRNN
      - Connectsionist Temporal Classification（CTC）損失
      - light backbone（MobileNetV3）
      - data augmentation（base data augmentation + RandAugment + TIAを採用）
          - base data augmentation（BDA）：回転、遠近法歪み、モーションブラー、ガウスノイズ等
        ![image](https://user-images.githubusercontent.com/9916906/104153783-9463f000-5426-11eb-9278-7d610a6090fe.png)
      - PACT quantization（MobileNetV3のhard swish向けの改良を実施）
      - cosine learning rate decay、learning rate warm-up
      - 入力画像とネットワークサイズの大小調整
      - FPGM Pruner Pruning
      - Remove SE（当該タスクでは、SEの精度貢献がほぼ無かったとのこと）
      - optimizerはAdam
  - データセットについて…
      - 中国語・英語認識のためのデータセット
          - 検出用：97,000枚
          - 方向分類用：600,000枚
          - テキスト認識用：17,900,000枚
      - フランス語、韓国語、日本語、ドイツ語でも検証を行われています
     ![image](https://user-images.githubusercontent.com/9916906/104153495-cde82b80-5425-11eb-88d5-c73bcf5b61fe.png)

<br/>

## リポジトリの動かし方

  - [QUICK INSTALLATION](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/installation_en.md)→[Quick start of Chinese OCR model](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/quickstart_en.md)という順番で進めると、先ず「中国語＋英語」の認識が実施できます
      - Google Colabにて、GPUによる推論を実施しようとしたのですが、paddle特有のエラーが出てしまい、それが解消できませんでした
      - Google Colabにて、CPUによる推論を実施したところ、上手くOCR認識を行えました
        ![11](https://user-images.githubusercontent.com/9916906/104206189-9653a080-5472-11eb-937e-c51cde974496.jpg)

  - 日本語のOCR認識は、上記「中国語＋英語」の認識手順を、以下記事に沿って少し変更すれば実施ができます
    https://zenn.dev/shimat/articles/6ac851fbba2e0bae05c8
    （※記事中のリポジトリへのリンクは、ブランチが少し古いので、その点だけ対応が必要です）
      - リポジトリ内に用意されている画像にて、OCRを実施した結果が以下となります
        ![japan_1](https://user-images.githubusercontent.com/9916906/104205409-b20a7700-5471-11eb-8635-17794eb6e102.jpg)
        ![japan_2](https://user-images.githubusercontent.com/9916906/104205418-b46cd100-5471-11eb-8d8a-6038aa896f8f.jpg)

  - detectionのモデルは、精度重視や、速度重視等、様々用意されているようですので、目的に応じて、切り替えられるようになっていると良さそうです
    https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0-rc1-0/doc/doc_en/models_list_en.md

<br/>

## ONNX変換について

以下のリポジトリにて、実現ができそうです。
https://github.com/PaddlePaddle/paddle2onnx

onnxコンパイルから、inference実施までのサンプルNotebookもありました。
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/examples/tutorial_dygraph2onnx.ipynb

**Comment by mucunwuxian** [comment]
# リサーチ結果（２）

結論として、PaddleOCRのonnx化が難しいことが分かりました。
以下、散文的になりますが、リサーチした結果を記載していきます。
こちらを基に、対策等話し合えますと、有り難い次第です。

<br/>

## Paddle2ONNXでサポートしていないオペレーターが、PaddleOCRのモデル内で使用されています

Paddle2ONNXのREADMEは以下となります。
https://github.com/PaddlePaddle/Paddle2ONNX#paddle2onnx

<br/>

Release Noteによれば、Paddleには、static graph modeと、dynamic graph modeとが存在するとのことです。
恐らく、build and runと、build by runかと思われます。
ビルドの際には、static graph modeが推奨されているようです。
https://www.paddlepaddle.org.cn/documentation/docs/en/release_note_en.html

<br/>

PaddleOCRのモデルは、以下リンクに紹介されています。
これらは、static graph modeにて保存されているものとなります。
https://github.com/PaddlePaddle/PaddleOCR#pp-ocr-20-series-model-listupdate-on-dec-15
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_en/models_list_en.md

<br/>

日本語のOCRを実施するのに必要な、推論用のモデルファイルをダウンロードしてみると、以下のようなレイアウトになっています。

`ch_ppocr_mobile_v2.0_det_infer`：文字位置のBoundingBoxを出力してくれる、検出モデル
`ch_ppocr_mobile_v2.0_cls_infer`：検出した文字BoundingBoxの向きを推定してくれるモデル（[default](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/cls/cls_mv3.yml)は、0° or 180°の2class識別で、[後者と識別された場合はBoundingBox画像を180°回転](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/tools/infer/predict_cls.py#L111)）
`japan_mobile_v2.0_rec_infer`：BoundingBox内画像の文言を認識してくれるモデル

```
.
├── ch_ppocr_mobile_v2.0_cls_infer
│   ├── __model__
│   ├── __params__
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
├── ch_ppocr_mobile_v2.0_cls_infer.onnx
├── ch_ppocr_mobile_v2.0_cls_infer.tar
├── ch_ppocr_mobile_v2.0_det_infer
│   ├── __model__
│   ├── __params__
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
├── ch_ppocr_mobile_v2.0_det_infer.tar
├── ch_ppocr_mobile_v2.0_rec_infer
│   ├── __model__
│   ├── __params__
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
├── ch_ppocr_mobile_v2.0_rec_infer.tar
├── japan_mobile_v2.0_rec_infer
│   ├── __model__
│   ├── __params__
│   ├── inference.pdiparams
│   ├── inference.pdiparams.info
│   └── inference.pdmodel
└── japan_mobile_v2.0_rec_infer.tar

```

<br/>

これらに対して、Paddle2ONNXを、READMEに従って適用していきます。
https://github.com/PaddlePaddle/Paddle2ONNX#static-computational-graph

<br/>

すると、3つの対象モデルの内、2つが失敗してしまいました。

`ch_ppocr_mobile_v2.0_det_infer`：検出モデル、×失敗
```
`!paddle2onnx --model_dir ./PaddleOCR/inference/ch_ppocr_mobile_v2.0_det_infer \
             --model_filename inference.pdmodel \
             --params_filename inference.pdiparams \
             --save_file ./onnx/ch_ppocr_mobile_v2.0_det_infer.onnx \
             --opset_version 9 \
             --enable_onnx_checker False
▼
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dev38/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.4', 'console_scripts', 'paddle2onnx')())
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/command.py", line 133, in main
    program2onnx(
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/command.py", line 106, in program2onnx
    p2o.program2onnx(
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/convert.py", line 30, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 133, in build
    OpMapper.check_support_status(paddle_graph, opset_version)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 123, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 1 ops are not supported yet
=========== nearest_interp_v2 ===========
```

`ch_ppocr_mobile_v2.0_cls_infer`：角度識別モデル、○成功
```
`!paddle2onnx --model_dir ./PaddleOCR/inference/ch_ppocr_mobile_v2.0_det_infer \
             --model_filename inference.pdmodel \
             --params_filename inference.pdiparams \
             --save_file ./onnx/ch_ppocr_mobile_v2.0_det_infer.onnx \
             --opset_version 9 \
             --enable_onnx_checker False
▼
2021-01-23 15:16:35 [INFO]	ONNX model saved in ./onnx/ch_ppocr_mobile_v2.0_cls_infer.onnx
```

`japan_mobile_v2.0_rec_infer`：文字認識モデル、×失敗
```
!paddle2onnx --model_dir ./PaddleOCR/inference/japan_mobile_v2.0_rec_infer \
             --model_filename inference.pdmodel \
             --params_filename inference.pdiparams \
             --save_file ./onnx/japan_mobile_v2.0_rec_infer.onnx \
             --opset_version 11 \
             --enable_onnx_checker False
▼
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dev38/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.4', 'console_scripts', 'paddle2onnx')())
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/command.py", line 133, in main
    program2onnx(
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/command.py", line 106, in program2onnx
    p2o.program2onnx(
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/convert.py", line 30, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 133, in build
    OpMapper.check_support_status(paddle_graph, opset_version)
  File "/opt/anaconda3/envs/dev38/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 123, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 2 ops are not supported yet
=========== rnn ===========
=========== fill_constant_batch_size_like ===========
```

<br/>

失敗の理由としては、以下Paddleオペレーターが、Paddle2ONNXでサポートされていないとのことでした。
  - `nearest_interp_v2`
  - `fill_constant_batch_size_like`
  - `rnn`

<br/>

尚、Paddle2ONNXがサポートしているオペレーターについての情報が以下となります。
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/en/op_list.md

こちらによれば、`nearest_interp_v2`と、`fill_constant_batch_size_like`とは、サポート対象となっているのですが、Paddle2ONNXのversionを幾つか試しても、エラー解消できませんでした。
`rnn`は、サポートに含まれていませんでした。

<br/>

PaddleOCRリポジトリにて、onnx関連のissueを探してみたところ、当面サポートしないとの記載が幾つか上がってきました。
Paddleには、Paddle Liteという、独自のmobile等への展開機構があるようで、そちらが有線であるようでした。

  - サポート無し、検討はしてみるとの旨
    https://github.com/PaddlePaddle/PaddleOCR/issues/150
  - 検出モデルは、X2Paddleにてonnx化できたが、認識モデルはできなかったとのこと
    https://github.com/PaddlePaddle/PaddleOCR/issues/213
  - X2Paddleにて、onnx化はできたが、runtimeエラーとなった旨
    https://github.com/PaddlePaddle/PaddleOCR/issues/373
  - 小職同様、onx変換時のエラー
    https://github.com/PaddlePaddle/PaddleOCR/issues/549
  - onnxをサポートしていない為、PaddleLiteを仕様下さいとの旨
    https://github.com/PaddlePaddle/PaddleOCR/issues/854
  - dynamic graph modeのPaddleOCRから、onnx化が可能とあるとの旨（しかしながら、学習済み推論用モデルは、依然としてstatic graph mode）

<br/>

PaddleOCRリポジトリの、onnx関連のissueを調べていると、X2Paddleというキーワードが上がってきたので調べてみると、幾つかのdeep learning frameworkを、paddleに変換するというものとのことでした。
また、その機能の一部として、以前は、`paddle → onnx`の機能もあったらしいが、それは現在、Paddle2ONNXに移管されたとのことです。

x2Paddleの、`paddle → onnx`の機能を使おうとすると、Paddle2ONNXを紹介されるだけで、機能しないように制御されている次第です。
```
!x2paddle -f paddle2onnx \
          -m ./PaddleOCR/inference/ch_ppocr_mobile_v2.0_cls_infer/ \
          -s ./onnx
▼
paddle.__version__ = 2.0.0-rc1
Paddle to ONNX tool has been migrated to the new github: https://github.com/PaddlePaddle/paddle2onnx
```

paddleのversionを、1.8.x等に調整してみても、同じメッセージが出力されました。

<br/>

また、Paddle2ONNXリポジトリの、ocr関連のissueも調べてみましたが、onnx化失敗を解消する方法等はあがってきませんでした。

<br/>

その他、ネット上で色々と検索を掛けてみたのですが、PaddleOCRのONNX化エラーを解消するための情報、かつ、信頼性の高い情報には、辿り着くことができませんでした。
直接的に、PaddleOCRの推論用モデルを、onnx化することは難しいように思えます。

<br/>

それでは、間接的に解決する方法は無いかと調べていると、以下のリポジトリを発見しました。
https://github.com/frotms/PaddleOCR2Pytorch

PddleOCRを、pytorchに変換するというものです。
convert用コードを、幾つか実装してくれているもののようです。
近日中に実装されたものであり、starも少ない為、信頼性如何は不明ですが、これを試してみようと思います。
上手くいけば、`paddle → pytorch → onnx`という変換ができるかもしれません。

（一旦、ここまでになります…、続きます…）

**Comment by mucunwuxian** [comment]
# リサーチ結果（３）

結論として、[PaddleOCR2Pytorch](https://github.com/frotms/PaddleOCR2Pytorch)というリポジトリを用いて、PaddleOCRのONNXエクスポートを実現できました。
PaddleOCRを、一度、Pytorchにコンバートしてから、torch.onnxを用いて、ONNXのsessionファイルをエクスポートします。

<br/>

## PaddleOCR2Pytorchについて




<br/>

## PaddleOCRのパイプライン別入力形式と、ONNXエクスポート時のdynamic_axesについて

### 全体像

<br/>

### Text Detection

<br/>

### Detection Boxes Recify

<br/>

### Text Recognition

<br/>

## Paddle2Pytorchの一般方法について、簡易的にまとめ


<br/>

**Comment by mucunwuxian** [comment]
# リサーチ結果（４）

## 「from shapely.geometry import Polygon」と「import pyclipper」の除去について

ひょっとすると、今後も同様の事象が起こるかもしれませんので、念の為、備忘として残させて頂こうと思います。

<br/>

paddle ocrにおいては、テキスト検出からテキスト認識へと、処理を移行する際に、以下のような処理を行っています。

![イラスト625](https://user-images.githubusercontent.com/9916906/109418451-cd264b80-7a0b-11eb-811e-778a03602f98.png)

<br/>

このような処理を行うに当たっての幾何計算に、`shapely.geometry` と `pyclipper` というライブラリを使用しています。
これらライブラリは、ailiaのrequirements.txtに載っていないものであり、ニッチなライブラリである為、numpyを用いた計算ロジックに置き換えたいと思います。

<br/>
<br/>

`shapely.geometry` については、以下のような計算処理が行われています。

```
from shapely.geometry import Polygon

unclip_ratio = 1.6

box = np.array([[1043., 118.], 
                [1267., 118.],
                [1267., 141.],
                [1043., 141.]])

poly = Polygon(box)
distance = poly.area * unclip_ratio / poly.length

print('distance =', distance)
```

その計算結果は、以下となります。

![image](https://user-images.githubusercontent.com/9916906/109410188-dd263700-79db-11eb-968b-b0feb6861594.png)

<br/>
<br/>

`shapely.geometry` の用途は、bboxの面積と、bboxの外周の長さとを求めている形になります。
その為、以下ロジックに置き換えることができました。

```
import numpy as np

unclip_ratio = 1.6

box = np.array([[1043., 118.], 
                [1267., 118.],
                [1267., 141.],
                [1043., 141.]])

poly_area = (np.sqrt(np.sum((box[0, :] - box[1, :])**2)) * 
             np.sqrt(np.sum((box[0, :] - box[3, :])**2)))
poly_length = (np.sqrt(np.sum((box[0, :] - box[1, :])**2)) + 
               np.sqrt(np.sum((box[0, :] - box[3, :])**2))) * 2

print('distance =', distance)
```

計算結果は、以下となります。

![image](https://user-images.githubusercontent.com/9916906/109410198-00e97d00-79dc-11eb-84fe-a3e70171841f.png)

<br/>
<br/>

尚、この計算結果の `distance` は、テキスト検出のbboxに対する、1回り外側の角丸外接矩形を生成するのに使用します。
具体的には、角丸部分の半径の大きさに採用します。

角丸部分の半径とは、以下図のような概念です。
半径が大きければ、角がより丸くなり、半径が小さければ、角の丸みが小さくなります。

<br/>

![image](https://user-images.githubusercontent.com/9916906/109410431-05169a00-79de-11eb-8020-ac2c6b11794a.png)

<br/>
<br/>

`pyclipper` は、その角丸の外接矩形を作成するのに使用されています。

例えば、以下のようなコードになります。

```
# import...
import pyclipper
import numpy as np
import matplotlib.pyplot as plt

# set value...
box = np.array([[100, 150], 
                [300, 150], 
                [300, 100], 
                [100, 100]])

# set param...
distance = 20.0

# ----------------------------------------------------------------
# target process
pco = pyclipper.PyclipperOffset()

pco.AddPath(box, pyclipper.JT_ROUND, pyclipper.ET_CLOSEDPOLYGON)

expanded = pco.Execute(distance)
expanded = np.array(expanded[0])
# ----------------------------------------------------------------

# show...
plt.figure(figsize=(10, 10), dpi=100)
plt.scatter(box[:, 0], box[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([box[:, 0], box[[0], 0]]), 
         np.concatenate([box[:, 1], box[[0], 1]]), linewidth=5, alpha=0.5)
plt.scatter(expanded[:, 0], expanded[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([expanded[:, 0], expanded[[0], 0]]), 
         np.concatenate([expanded[:, 1], expanded[[0], 1]]), linewidth=5, alpha=0.5)
plt.grid(True)
plt.axis('equal')
plt.gca().invert_yaxis()
plt.show()
```

その計算結果は、以下となります。

![image](https://user-images.githubusercontent.com/9916906/109415604-f7bcd800-79fc-11eb-93eb-cc798feff31d.png)

<br/>
<br/>

元のbboxが傾いている場合だと、以下のようなコードと計算結果になります。

```
# import...
import pyclipper
import numpy as np
import matplotlib.pyplot as plt

# set value...
box = np.array([[563.15510, 306.31964],
                [952.10626, 352.72858],
                [946.29425, 401.43854],
                [557.34310, 355.02960]])

# set param...
distance = 20.0

# ----------------------------------------------------------------
# target process
pco = pyclipper.PyclipperOffset()

pco.AddPath(box, pyclipper.JT_ROUND, pyclipper.ET_CLOSEDPOLYGON)

expanded = pco.Execute(distance)
expanded = np.array(expanded[0])
# ----------------------------------------------------------------

# show...
plt.figure(figsize=(10, 10), dpi=100)
plt.scatter(box[:, 0], box[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([box[:, 0], box[[0], 0]]), 
         np.concatenate([box[:, 1], box[[0], 1]]), linewidth=5, alpha=0.5)
plt.scatter(expanded[:, 0], expanded[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([expanded[:, 0], expanded[[0], 0]]), 
         np.concatenate([expanded[:, 1], expanded[[0], 1]]), linewidth=5, alpha=0.5)
plt.grid(True)
plt.axis('equal')
plt.gca().invert_yaxis()
plt.show()
```

![image](https://user-images.githubusercontent.com/9916906/109415663-53876100-79fd-11eb-896b-868d0582af61.png)

<br/>
<br/>

上記処理を、numpyのスクラッチで実施する場合、以下のようなアルゴリズムとなります。

```
（１）青色のbbox矩形の上辺と、x軸とが、平行になるように、回転補正する
（２）青色のbboxの四角に、任意半径の円座標を展開する
（３）（２）の内、角丸矩形の、内側に入り込んでいないい点だけを残す
```

<br/>

これを、プログラムで書くと、以下のようになりました。
尚、コード中、法則性に若干の違和感がある箇所があるかもしれませんが、それは `pyclipper` との同値を取るために、調整した箇所となっています。

```
# import...
import cv2
import numpy as np
import matplotlib.pyplot as plt

# set value...
box = np.array([[563.15510, 306.31964],
                [952.10626, 352.72858],
                [946.29425, 401.43854],
                [557.34310, 355.02960]])

# set param...
distance = 20.0

# ----------------------------------------------------------------
# target process

# calc angle between upper side of bbox with x axis
u = box[1] - box[0]
v = box[1] - box[0]
v[1] = 0
i = np.inner(u, v)
n = np.linalg.norm(u) * np.linalg.norm(v)
c = i / n
angle = np.rad2deg(np.arccos(np.clip(c, -1.0, 1.0)))

# rotate coordinate
def xyrotate(coord_xy, angle, center_xy):
    # exec rotate
    rotation_matrix = cv2.getRotationMatrix2D((center_xy[0], center_xy[1]), angle, 1)
    # make variable for output
    coord_xy_rotated = np.zeros(np.shape(coord_xy))
    # loop of coordinate
    for coord_i in range(len(coord_xy)):
        # set x, y
        coord_x_tmp = coord_xy[coord_i, 0]
        coord_y_tmp = coord_xy[coord_i, 1]
        # slide to suit center of rotation
        coord_x_tmp -= center_xy[0]
        coord_y_tmp -= center_xy[1]
        # exec rotation
        coord_xy_tmp        = np.array([coord_x_tmp, coord_y_tmp])[:, np.newaxis]
        rotation_matrix_tmp = np.array([[np.cos(-angle/180*np.pi), 
                                         -np.sin(-angle/180*np.pi)], 
                                        [np.sin(-angle/180*np.pi), 
                                         np.cos(-angle/180*np.pi)]])
        coord_xy_tmp        = rotation_matrix_tmp @ coord_xy_tmp
        # re-slide to suit center of rotation
        coord_xy_tmp     = coord_xy_tmp.reshape(-1)
        coord_xy_tmp[0] += center_xy[0]
        coord_xy_tmp[1] += center_xy[1]
        # stock
        coord_xy_rotated[coord_i, :] = coord_xy_tmp
    
    return coord_xy_rotated

# exec coordinates rotation 
box_ = xyrotate(coord_xy=box, angle=angle, center_xy=np.mean(box, axis=0))

# calculate circle coordinates
pitch = 10
x_upper = np.cos(np.arange(1, 0, (-1/pitch)) * np.pi) * distance
y_upper = -np.sqrt(distance**2 - x_upper**2)
x_lower = np.cos(np.arange(0, 1, (1/pitch)) * np.pi) * distance
y_lower = np.sqrt(distance**2 - x_lower**2)
x = np.concatenate([x_upper, x_lower])
y = np.concatenate([y_upper, y_lower])
circle = np.concatenate([x[:, np.newaxis], y[:, np.newaxis]], axis=1)

# calculate circle coordinates around four corners
expanded = []
for box_tmp in box_:
    expanded.append(circle + box_tmp)
expanded = np.array(expanded).reshape(-1, 2)

# narrow down circle coordinates to outside 
expanded = expanded[[25, 26, 27, 28, 29, 30, 50, 51, 52, 53, 54, 55, 
                     75, 76, 77, 78, 79, 60,  0,  1,  2,  3,  4,  5]]

# exec coordinates re-rotation 
expanded = xyrotate(coord_xy=expanded, angle=-angle, center_xy=np.mean(box_, axis=0))

# ----------------------------------------------------------------

# show...
plt.figure(figsize=(10, 10), dpi=100)
plt.scatter(box[:, 0], box[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([box[:, 0], box[[0], 0]]), 
         np.concatenate([box[:, 1], box[[0], 1]]), linewidth=5, alpha=0.5)
plt.scatter(expanded[:, 0], expanded[:, 1], s=300, alpha=0.5)
plt.plot(np.concatenate([expanded[:, 0], expanded[[0], 0]]), 
         np.concatenate([expanded[:, 1], expanded[[0], 1]]), linewidth=5, alpha=0.5)
plt.grid(True)
plt.axis('equal')
plt.gca().invert_yaxis()
plt.show()

expanded_ = expanded
```

計算結果は、以下となります。

![image](https://user-images.githubusercontent.com/9916906/109417313-70746200-7a06-11eb-802f-ee7cd4ab4818.png)

<br/>

出力値の比較をしてみると、以下のようになりました。
このケースで言えば、問題が無さそうでした。

![image](https://user-images.githubusercontent.com/9916906/109417341-97329880-7a06-11eb-86a0-5855c7da1a80.png)

<br/>
<br/>

しかし、その後、幾つかのケースで、同値確認を行ってみたところ、並びや、点の選定基準、及び、作成数などで、微妙に差が生じました。
しかし、その差が実処理に問題の無い範囲であることを、後続の処理結果にて、差分を取って確認をしました。
値のスケールと比較して、凡そ1%未満の差分のみとなっております。
念の為、同値確認を行った版については、githubの履歴（33e8ccc）に残させて頂きました。
尚、最終的な結果についても、問題はありませんでした。

<br/>

以上、ライブラリを除去にて行ったことの備忘でした。

**Comment by mucunwuxian** [comment]
PaddleOCRでの学習方法について、https://github.com/axinc-ai/ailia-models/issues/310 に引き続きます。
日本語と英語の、文字内容認識モデルの、精度向上を目指すものとなります。
