### ISSUE TITLE
specify directory name for args.input

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#311]
- ディレクトリ内のすべての画像に対して推論を行う
- 同じディレクトリ内に個々に出力をsave
- videoに対してはどうする？
- arcfaceみたいな特殊系は別途検討が必要
---
1. `glob.glob`で png, jpeg, jpgなどよく使われるものを回収
2. 推論ループ
3. 保存ファイル名は適宜update

--- 
- こんな感じでクラス作ったほうが後々管理が楽かもしれない，要検討
```python3
class ImageReader:
    def __init__(self, file_names):
        self.file_names = file_names
        self.max_idx = len(file_names)

    def __iter__(self):
        self.idx = 0
        return self

    def __next__(self):
        if self.idx == self.max_idx:
            raise StopIteration
        img = cv2.imread(self.file_names[self.idx], cv2.IMREAD_COLOR)
        if img.size == 0:
            raise IOError(
                'Image {} cannot be read'.format(self.file_names[self.idx])
            )
        self.idx = self.idx + 1
        return img

```

**Comment by itsmeterada** [comment]
出力ディレクトリはやはり分けた方が良いと思いました。繰り返しテストする際に、ディレクトリ内に画像を入れて推論→結果確認→入力ディレクトリ内の画像を消して新しい画像を入れる→推論、といった流れが考えられます。
よって出力ディレクトリの命名規則を決めてそこに推論結果を保存するようにしましょう。
出力ディレクトリは「入力ディレクトリ.result」とかが考えられます。

**Comment by sngyo** [comment]
### 進捗 (efficientnetのみ仮実装)
- `-i`オプションにディレクトリ名が指定された場合，対応するモダリティー(画像/動画/音声)のファイルを拾ってきてリスト化
- logger導入
<img width="689" alt="スクリーンショット 2020-12-22 16 00 15" src="https://user-images.githubusercontent.com/45060776/102859345-16d44200-446f-11eb-8613-5e9f1d0f9d8c.png">
