### ISSUE TITLE
ADD yet another anime segmenter

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#317]
https://github.com/zymk9/Yet-Another-Anime-Segmenter

**Comment by kyakuno** [comment]
mot

**Comment by zhaochow** [comment]
@kyakuno The export of this model is trickier than I expected. It does not use a straightforward model under `nn.Module` with the `forward` method accepting a simple `torch.Tensor` and as such, I have been refactoring the code a bit to get around this.

Moreover, even after exporting the ONNX model, I get the following error when running with ailia:
![image](https://user-images.githubusercontent.com/18057671/104390972-3d732d80-5582-11eb-93ec-697842e19a0c.png)

Would you have an idea in which cases a dead-lock could be caused?

**Comment by kyakuno** [comment]
@zhaochow Please implement --onnx option using onnx runtime for test. ailia SDK 1.2.6 will fix this issue.

**Comment by zhaochow** [comment]
@kyakuno Would you know where I can find some anime character images free to use as a sample? Also, there seem to be 2 models (CondInst and SOLOv2). I am finishing the export of SOLOv2 but should I also export the second one?

**Comment by kyakuno** [comment]
You only need to export one model. So you do not need export condinst model.

**Comment by kyakuno** [comment]
Please use some anime image download from https://unity-chan.com/contents/guideline/ .
And please add this license.
© Unity Technologies Japan/UCL

**Comment by zhaochow** [comment]
> You only need to export one model. So you do not need export condinst model.

Understood!

I added the sample image and the image license in README.md. Please see the related PR (#337) for the changes.
