### ISSUE TITLE
Refactoring Future work

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#40]
- 似たような内容を (使いまわせないのは仕方ないとして) 結構違う方法で書いてしまっているので，`net.predict()`が全体に有効になった時点で(?)一旦全モデルをrefactorしようと思います．
- その上で，ある程度テンプレ化したものをwikiに載せておきます．

## 要確認事項
- [x] refactoringブランチからPRをどのくらいの頻度で出せばいいのか
- [x] 原則一つのスクリプトにまとめるべきか，`utils.py`とメインスクリプトに分けても大丈夫か (`load_image`など)

**Comment by kyakuno** [comment]
・全てのサンプルでWEBカメラ入力に対応したい
と考えていまして、utilフォルダを作ってそこにまとめてしまうのが良い気がします。

**Comment by sngyo** [comment]
ailia-models
  |- utils  (教養関数)
  |     |- movie.py  (未定)
  |     |- image.py  (未定)
  |
  |- bert
  |     |- bert.py
  |     |- bert_util.py
  |
  |- lightweight-human-pose-estimation-3d
  |     |- lightweight-human-pose-esatimation-3d.py
        |- lightweight-human-pose-esatimation-3d_util.py
...

**Comment by kyakuno** [comment]
そうですね。そんな感じでお願いできればと思います。

**Comment by kyakuno** [comment]
requirements.txtも準備した方が良さそう。

**Comment by sngyo** [comment]
そうですね，本来はpipenvとかでしっかり管理すべきなのかもしれませんが．．．
次のようなワークフローで問題ないでしょうか

1. code-refactoring
2. README.md のupdate (体裁を整える？)
3. pipenvかなにかでクリーンな状況を作成し必要パッケージの洗い出し・モデルごとにrequirements.txtの作成

**Comment by kyakuno** [comment]
はい、上記の流れで問題ありません。

**Comment by sngyo** [comment]
- [ ] 基本的に5回実行してailiaの推論時間を計測しているが，実利用の際にはループ構造ごと不要である点をREADMEに記載した方がいいかもしれない

**Comment by sngyo** [comment]
requirements.txtまで作成したので一旦終了
