### ISSUE TITLE
ADD PaDiM-Anomaly-Detection-Localization-master

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#401]
https://github.com/xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master
Apache

**Comment by kyakuno** [comment]
最も性能が高い
https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad

**Comment by kyakuno** [comment]
ailia-modelsのカテゴリはanomaly_detectionを新規追加。

**Comment by kyakuno** [comment]
resnet18のpretrained modelの各レイヤーのfeature mapを使ってvectorを作り、分散を計算、そこから離れたものを以上とする。

**Comment by kyakuno** [comment]
再学習不要の異常検知なのに、最も性能が高くなっている。

**Comment by kyakuno** [comment]
ailiaの場合はget_blob_dataを使って中間データを取得可能。

**Comment by kyakuno** [comment]
機能1：データセットフォルダを指定してそこから分散を計算してファイルに保存
機能２：画像ファイルを指定してセグメンテーションと正常/異常を判定する

**Comment by ooe1123** [comment]
torch1.7、opset_version=11でエクスポートしたとき、それぞれのモデルの各レイヤのアウトプットは次のようになった。

○ wide_resnet50_2
[layer1]
 355 -> Relu_24 -> 356
 (n,256,56,56)
[layer2]
 397 -> Relu_53 -> 398
 (n,512,28,28)
[layer3]
 459 -> Relu_96 -> 460
 (n,1024,14,14)

○ resnet18
[layer1]
 139 -> Relu_12 -> 140
 (n,64,56,56)
[layer2]
 155 -> Relu_23 -> 156
 (n,128,28,28)
[layer3]
 171 -> Relu_34 -> 172
 (n,256,14,14)
