### ISSUE TITLE
ADD swiftnet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#409]
https://github.com/orsic/swiftnet
gpl

**Comment by hattan1990** [comment]
”gtFine_trainvaltest”を”labels”
”leftImg8bit_trainvaltest”を”rgb”
に変更して、”Cityscapes”フォルダを作成

**Comment by hattan1990** [comment]
[データローダー：/swiftnet/data/cityscapes/cityscapes.py]
imagesを".ppm"から".png"を取得できるように変更
　×self.images = list(sorted(self.images_dir.glob('*/*.ppm')))
　○self.images = list(sorted(self.images_dir.glob('*/*.png')))

**Comment by hattan1990** [comment]
ONNXエクスポートの際に、randモジュールでエラーが発生するため、
numpy処理で書換を行う
