### ISSUE TITLE
ADD FLAVR

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#416]
https://github.com/tarun005/FLAVR

**Comment by kyakuno** [comment]
Apache
Frame interpolation

**Comment by ooe1123** [comment]
GUPまわりでエラーが発生するため、test.pyの以下を書き換える
os.environ["CUDA_VISIBLE_DEVICES"]='7'
↓
os.environ["CUDA_VISIBLE_DEVICES"]='0'
