### ISSUE TITLE
ADD Detect-Utility-Poles

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#429]
https://github.com/hiugiak/Detect-Utility-Poles
MIT

**Comment by kyakuno** [comment]
COCO DATASET

**Comment by seijikojima** [comment]
1. モデルの動作確認
・mask_rcnn_poles_resnet50.h5がinspect_validation_resnet50.ipynb上で正常に動作することを確認.
![result](https://user-images.githubusercontent.com/19236873/119360990-24c01480-bce6-11eb-959c-e08928cae78a.png)

2. .onnx形式へ変換
・mask_rcnn_poles_resnet50.h5を以下のissueを参考に.onnxへ変換, mask-rcnn用の変換スクリプト.
　https://github.com/onnx/keras-onnx/issues/568
・custom layerのconvert_tf_crop_and_resize関数をtest_utilsから読み込むのではなく, 直接書き加えることで動作可能.
　https://github.com/onnx/keras-onnx/issues/450

**Comment by seijikojima** [comment]
onnxエクスポートしてみましたが，ailiaでロードすると以下のエラーが発生します．
```
ailia.core.AiliaUnsupportNetException: code : -9
+ error detail : Layer:roi_align_classifier/CropAndResize_crop_and_resize(CropAndResize) Error:Unsupported layer: CropAndResize
```
どういった種類のエラーで，どういった対処をしていけば良いか，
教えていただきたいです．
こちらのpole detectionのmodelをexportする際に，keras2onnxライブラリにおいて，
set_converter()を用いて，CropAndResizeというlayerを登録する必要があり，登録しました．

現在，以下のissueを参考にしています．https://github.com/axinc-ai/ailia-models/issues/385
onnxruntimeでは，適切に動作するようです．

**Comment by kyakuno** [comment]
CropAndResize、onnxの公式のオペレータではなさそうで、ONNXRuntimeの独自オペレータなんですかね。
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/contrib_ops/cpu/crop_and_resize.cc
とりあえず、onnxruntimeで動作すれば問題ありませんので、--onnxオプションでonnxruntimeも使えるようにして、PRいただけますでしょうか。

**Comment by seijikojima** [comment]
承知いたしました. --onnxオプションでonnxruntimeを使えるようにしてPRします.

**Comment by seijikojima** [comment]
`results = sess.run(None, {"input_image": molded_images.astype(np.float32),"input_anchors": anchors,"input_image_meta": image_metas.astype(np.float32)})`
runtimeで推論する際，molded_images，anchors，image_metasの3つの入力が必要となり，
これらが，mrcnnのclass情報を必要とするため，考慮して前処理を作成中です．
https://github.com/axinc-ai/ailia-models/tree/master/object_detection/maskrcnn
こちらの一般的なmask-rcnnと入力が異なることが気になりますが，進めてまいります．

**Comment by kyakuno** [comment]
CropAndResizeを使用しない形で再エクスポートしたい。
エクスポートしてくれる方を募集中。

**Comment by ooe1123** [comment]
tensorflow1ベース

最新のPythonではtensorflow1をサポートしていないので、tensorflow1での環境構築は難易度が高い。
tensorflow2では、以下のエラーが解消できない。

```
Traceback (most recent call last):
  File "/workspaces/dev/Detect-Utility-Poles/cli.py", line 44, in <module>
    model = modellib.MaskRCNN(mode="inference", config=config, model_dir=LOGS_DIR)
  File "/workspaces/dev/Detect-Utility-Poles/Mask_RCNN/mrcnn/model.py", line 1844, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/workspaces/dev/Detect-Utility-Poles/Mask_RCNN/mrcnn/model.py", line 2042, in build
    fpn_classifier_graph(rpn_rois, mrcnn_feature_maps, input_image_meta,
  File "/workspaces/dev/Detect-Utility-Poles/Mask_RCNN/mrcnn/model.py", line 958, in fpn_classifier_graph
    mrcnn_bbox = KL.Reshape((s[1], num_classes, 4), name="mrcnn_bbox")(x)
  File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py", line 571, in _ExtractInputsAndAttrs
    raise ValueError(
ValueError: Exception encountered when calling layer "mrcnn_bbox" (type Reshape).

Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

Call arguments received by layer "mrcnn_bbox" (type Reshape):
  ~ inputs=tf.Tensor(shape=(1, None, 8), dtype=float32)
```

**Comment by kyakuno** [comment]
tensorflowが古く、対応が困難そうなので、非対応とします。
