### ISSUE TITLE
ADD RONELD-Lane-Detection

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#432]
https://github.com/czming/RONELD-Lane-Detection
 LGPL-3.0 License

**Comment by hattan1990** [comment]
SCNNまたはENet-SAD（ADD Codes-for-Lane-Detection #426）のモデル（推論結果：probability map）が必要となるため、
こちらの対応に関しては一旦ペンディングにさせていただきます。
（推論自体は、リポジトリ内の「画像、probability map」を用いて実行可能です）

**Comment by kyakuno** [comment]
@hattan1990 検証、ありがとうございます。ENet-SADを先行して評価してみたいと考えていまして、ENet-SADに限定して、#426 の作業を進めていただくことは可能でしょうか。

**Comment by hattan1990** [comment]
@kyakuno 
承知しました。
#426 の作業に対応いたします。
