### ISSUE TITLE
Unexpected Results GAZEML

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#45]
refactoringの結果がうまくいかないため masterブランチのgazezml.pyを実行してみたところ，次のような結果となり README.md と同じ出力が得られない．

### 環境
- Macbook pro 2017
- ailia (axell-corp/ailia-aeplugin/issues/24のものを使用)

![output](https://user-images.githubusercontent.com/45060776/78535761-ad040180-7827-11ea-873a-78c44d4064c8.png)

**Comment by sngyo** [comment]
画像 (151, 245, 3) にplotする前の出力は次のようになっていた．
<img width="368" alt="スクリーンショット 2020-04-06 17 09 04" src="https://user-images.githubusercontent.com/45060776/78536786-5bf50d00-7829-11ea-97fc-552d9c1808a5.png">

**Comment by kyakuno** [comment]
MacのGPUがFP16な関係でオーバフローするようです。

data = data / 255.0 *2 -1.0
を
data = data / 255.0 -0.5
に変更してみて頂けますでしょうか。

**Comment by sngyo** [comment]
動きました．．．
preprocess方法を学習時と変更することには抵抗がありますが，osを検知してMacの時だけ上記のようにすればいいのでしょうか？
 (他のモデルで出会ったことがないエラー事例です．．．)

![tmp](https://user-images.githubusercontent.com/45060776/78542214-cf9b1800-7831-11ea-9745-ca4cf96a6565.png)

**Comment by kyakuno** [comment]
はい、現状はMacの場合だけ切り替えください。将来的にはFP16フラグで切り替えようと思います。

**Comment by sngyo** [comment]
```python
import platform
if platform.system() == 'Darwin'
```
で識別し，分岐することで解決
