### ISSUE TITLE
Add preprocess for mmfashion

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#454]
現在のmmfashionだと、下記の動画を入力した場合に不正なBoundingBoxが出力される。
https://pixabay.com/ja/videos/%E5%A5%B3%E6%80%A7-%E3%83%A2%E3%83%87%E3%83%AB-%E3%83%95%E3%82%A9%E3%83%88-%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3-22601/

<img width="752" alt="スクリーンショット 2021-05-07 14 26 59" src="https://user-images.githubusercontent.com/38881041/117401866-4d06ef80-af40-11eb-8aaf-90b9122f3ed0.png">

前処理でyolov3を使用するなどで改善余地があるか検討する。

**Comment by kyakuno** [comment]
優先度は低め。

**Comment by ooe1123** [comment]
訓練に使っているデータセットが背景がないものみたいなので、背景があると弱いみたいですね。
http://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html

yoloでpersonと検出した部分以外をマスクして推論にかけてみても微妙な感じです。

![image](https://user-images.githubusercontent.com/29946532/117662687-cb7ebe00-b1da-11eb-8dbb-074dac80d2ec.png)
![image](https://user-images.githubusercontent.com/29946532/117662739-dcc7ca80-b1da-11eb-8b67-c190f948f477.png)

**Comment by ooe1123** [comment]
背景は完全に消したほうが良いように思い、human-part-segmentation ( https://github.com/axinc-ai/ailia-models/tree/master/image_segmentation/human_part_segmentation ) を利用して、人物部分以外をマスクしてみました。

![image](https://user-images.githubusercontent.com/29946532/117663630-d7b74b00-b1db-11eb-96d0-b64b663b4679.png)
![image](https://user-images.githubusercontent.com/29946532/117663669-e43ba380-b1db-11eb-97cf-11caa7757ec8.png)
![image](https://user-images.githubusercontent.com/29946532/117663701-ebfb4800-b1db-11eb-98a5-1865d400e94d.png)
```
+ idx=0
  category=4[ outer ]
  prob=0.9572299122810364
  x=0.24614646973986717
  y=0.29805293414434825
  w=0.23932511193659173
  h=0.644030939203857
+ idx=1
  category=6[ bag ]
  prob=0.6910659074783325
  x=0.3305239976264476
  y=0.2832934205482002
  w=0.17229570463286217
  h=0.6143559223230513
+ idx=2
  category=8[ headwear ]
  prob=0.8392050266265869
  x=0.3097085147202827
  y=0.06966990530972335
  w=0.10862783211994778
  h=0.16911540239423464
+ idx=3
  category=11[ footwear ]
  prob=0.32846754789352417
  x=0.4388272790449733
  y=0.5806843352433361
  w=0.07595065720616201
  h=0.2989296859223546
```
bagは消えてしまいますが、BoundingBoxでマスクするよりはよさそうです。

---

人物のパーツが飛び島になってしまうことがあるので、OpenCVでクロージング処理( http://labs.eecs.tottori-u.ac.jp/sd/Member/oyamada/OpenCV/html/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html )を行い、一つのまとまった領域になるようにしてみました。
（この場合、クロージングに使うカーネルサイズをどう決めるかも課題になります）

![image](https://user-images.githubusercontent.com/29946532/117663798-07665300-b1dc-11eb-8dab-8bccea44cd60.png)
![image](https://user-images.githubusercontent.com/29946532/117663826-0df4ca80-b1dc-11eb-9444-4bd1da37b060.png)
![image](https://user-images.githubusercontent.com/29946532/117663852-14834200-b1dc-11eb-8140-da8a5d182802.png)
```
+ idx=0
  category=3[ dress ]
  prob=0.6241986155509949
  x=0.28099923475994837
  y=0.29590188859930333
  w=0.2012619309594261
  h=0.6701438299866216
+ idx=1
  category=4[ outer ]
  prob=0.9640327095985413
  x=0.2465599676785309
  y=0.29765208896026857
  w=0.24587183925479678
  h=0.6263021490685582
+ idx=2
  category=6[ bag ]
  prob=0.8711276054382324
  x=0.39764395981458617
  y=0.2304274600619068
  w=0.12269050397188636
  h=0.6396751588688914
+ idx=3
  category=7[ neckwear ]
  prob=0.34352144598960876
  x=0.29393051105883855
  y=0.2713479579746819
  w=0.17201758167291098
  h=0.6112487990174424
```

**Comment by kyakuno** [comment]
確認、ありがとうございます！
事前に背景切り抜きをすると良さそうですね。
モデルとしては、u2netを使うのが良さそうに考えていまして、u2netを使用するオプションを追加してPRをいただくことは可能でしょうか。
