### ISSUE TITLE
GoogLeNet Preprocessing

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#46]
ref: https://github.com/sngyo/ailia-models/tree/refactoring/googlenet

## 1. ailia.Classifier
ailia.Net に統一したいですね (etlも同様)
- 入力時のshapeが変わるのがトリッキーかと思います．

## 2.  Preprocess
どうやらそれなりの精度で実行はできているのですが，少なくとも [本家 PyTorch版](https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/pytorch_vision_googlenet.ipynb)とはだいぶ Preprocessが異なっているように見えます．

- ImageNet用のnoramlizeをかけていない
- なぜか入力が4チャンネルになっている

**Comment by sngyo** [comment]
現段階ではとりあえず Classifier のままリファクタしてあります

**Comment by sngyo** [comment]
vgg16モデルで判明した通り， 現状のclassifierでは適切な前処理を実行できていないので Net推奨．

**Comment by itsmeterada** [comment]
ただそれだとClassifierの存在意義が低くなるので、存在意義を示せるように（使う意味があるように）する必要がある。
