### ISSUE TITLE
ADD openmmlab indexnet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#473]
https://github.com/open-mmlab/mmediting#readme
apache

**Comment by kyakuno** [comment]
Deep image matting model

**Comment by kyakuno** [comment]
Same kind another model : https://github.com/axinc-ai/ailia-models/tree/master/image_segmentation/deep-image-matting

**Comment by Shysto** [comment]
First attempt: https://github.com/axinc-ai/ailia-models/pull/497
