### ISSUE TITLE
ADD Fashion Recognition and Retrieval

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#498]
https://github.com/open-mmlab/mmfashion

**Comment by Shysto** [comment]
@kyakuno 
Model too large to be exported in one ONNX file.
Had to use the `use_external_data_format=True` [option](https://pytorch.org/docs/stable/onnx.html#use-external-data-format) of the `torch.onnx.export()` function.
But ONNX file separated in several files is not recognized by ailia:
`ailia.core.AiliaException: code : -128 + error detail : Invalid onnx data length.`

**Comment by kyakuno** [comment]
@Shysto Could you try to implement using onnxruntime? ailia SDK will fix the issue.
