### ISSUE TITLE
ADD transformer-cnn-emotion-recognition

### ISSUE THREAD

**Issue by ytknzw** [axinc-ai/ailia-models#522]
https://github.com/IliaZenkov/transformer-cnn-emotion-recognition

**Comment by ytknzw** [comment]
公開されている学習済みモデルの重みがモデルの構造と一致せず、学習が必要なようです。

**Comment by ooe1123** [comment]
読み込み可能な学習済みモデルがないため、独自に学習を行った。
公式で公開しているほど精度がでない。
- オリジナルリポジトリで公開されている結果
![image](https://user-images.githubusercontent.com/29946532/129443481-352d2410-35d4-45f6-aaed-cd8b76574f1d.png)
- 独自に学習(SGD lr=0.01, weight_decay=1e-3, momentum=0.8)
<img width="353" alt="torch1 6" src="https://user-images.githubusercontent.com/29946532/129443465-7a560b97-5c8d-436a-92f7-b53d31a15ebe.png">

パラメータを少し変えて試してみても、改善は得られない

- SGD lr=0.001で学習
<img width="435" alt="lr0 001" src="https://user-images.githubusercontent.com/29946532/129443623-015977d6-7393-4222-a6df-afe1cb59c904.png">
- SGD momentum=0.6で学習
<img width="378" alt="momentum0 6" src="https://user-images.githubusercontent.com/29946532/129443659-c907e298-6b7a-4c33-bd15-31be99f48ae3.png">
