### ISSUE TITLE
ADD abd net

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#536]
person reid model
https://github.com/VITA-Group/ABD-Net

**Comment by kyakuno** [comment]
mit

**Comment by sabosantech** [comment]
market1501 datasetにおいての評価プログラム実行方法
`python train.py -s market1501 -t market1501  --evaluate --load-weights market_checkpoint_best.pth.tar`

**Comment by sabosantech** [comment]
(1, 3, 256, 128)のサイズで，Resnet50ベースのabdnetへ入力．
Global Average Pooling後，(1, 3072)の特徴ベクトルを得る．
その特徴ベクトルのユークリッド距離によって，画像の類似度を算出．

market1501 datasetの評価データでは，query画像3,368枚，gallery画像15,913枚用意されている．
評価プログラムでは，3368*15913の距離行列を作成し，top-k rankを算出している．

**Comment by sabosantech** [comment]
類似度をベクトルの内積から論文で採用されていたユークリッド距離へ変更．
ユークリッド距離の場合の方が精度が良い傾向．以下2つのqueryの実行結果例．

内積
![outpu1_dot](https://user-images.githubusercontent.com/86791143/131673612-957239f3-b684-4e40-a452-1a0c867392fe.png)
![output2_dot](https://user-images.githubusercontent.com/86791143/131674385-4e3f42df-3c3e-4fc6-b5f0-0a0f95be4a7a.png)

ユークリッド距離
![output1_ed](https://user-images.githubusercontent.com/86791143/131673642-30578611-4afc-4925-9aa3-bab26b6aa80a.png)
![output2_ed](https://user-images.githubusercontent.com/86791143/131674095-76d20532-e378-4bb3-8bfa-e4aa74824231.png)

**Comment by sabosantech** [comment]
person reid baselineのREADMEで使用されていたquery画像を使用した結果．
![output](https://user-images.githubusercontent.com/86791143/131678214-459e4678-aea3-4deb-a57f-1d17bf62ca61.png)

**Comment by sabosantech** [comment]
Duke datasetにおける結果2例．
![output_duke1](https://user-images.githubusercontent.com/86791143/132009385-6787f95c-11e3-444e-a9dd-58629b2bfdc8.png)
![output_duke2](https://user-images.githubusercontent.com/86791143/132009412-c62566bc-6264-48ee-a6a4-ef9d37b1d829.png)

MSMT17 datasetは[private issue](https://github.com/KaiyangZhou/deep-person-reid/issues/104)のため? download pageにアクセスできなかったです．
