### ISSUE TITLE
RAM usage issue on PaddleOCR

### ISSUE THREAD

**Issue by Belial-public** [axinc-ai/ailia-models#542]
Depending on image ratio, PaddleOCR scales the image to huge sizes internally which uses a lot of RAM and can crash the script.

Original dimensions: 148x717
Image: https://axincai.slack.com/archives/CMB1C68BZ/p1627550301135100
(1, 3, 6208, 1280)
Maximum memory usage: 8577.7265625

Original dimensions: 529x1097
Image: https://axincai.slack.com/archives/CMB1C68BZ/p1627550340135800
(1, 3, 2656, 1280)
Maximum memory usage: 3963.0234375

Original dimensions: 717x51
Image: https://axincai.slack.com/archives/CMB1C68BZ/p1627550457136800
(1, 3, 1280, 17984)
Maximum memory usage: 12505.8515625 (hit my max RAM, used disk swap 25GB+)

How to replicate:
`python paddleocr.py --env_id -1 --case=server -i test.png`

Added code:
```
if __name__ == '__main__':
    from memory_profiler import memory_usage
    mem_usage = memory_usage(main)
    print('Maximum memory usage: %s' % max(mem_usage))
```

**Comment by mucunwuxian** [comment]
Thank you for your infomation, it's my thoughtless!🙇
I fix and issuing a PR.
https://github.com/axinc-ai/ailia-models/pull/543

At first, the default is to set an upper limit for the image size.
Moreover, the processing policy for the image size can be selected as an option faithfully to the original specifications.
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/doc/doc_en/inference_en.md

I wrote the details in the readme.
https://github.com/axinc-ai/ailia-models/tree/paddleocr_limit_type/text_recognition/paddleocr#usage
