### ISSUE TITLE
ADD rinna gpt2

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#563]
https://github.com/rinnakk/japanese-pretrained-models
apache

**Comment by kyakuno** [comment]
gpt2は文章生成モデル
https://ledge.ai/rinna-gpt-2-bert/

**Comment by kyakuno** [comment]
推論デモ
https://huggingface.co/rinna/japanese-gpt2-small

**Comment by hattan1990** [comment]
公式で指定されている方法でONNXエクスポートを行うと本来の次元数が変化してしまう。
（デモの場合はemb dimが32,000だが、onnxエクスポートを行うと768に減少してしまう）
`python -m transformers.onnx --model=rinna/japanese-gpt2-small onnx/rinna/japanese-gpt2-small/ --opset 11`

**Comment by hattan1990** [comment]
convert(framework="tf", model="rinna/japanese-gpt2-small", tokenizer=tokenizer,
                output=Path("./onnx/output.onnx"), opset=11, pipeline_name="text-generation")
でテキスト生成（model.generate）モデルをエクスポートしたが、テキスト生成モデルは出力されない。

**Comment by hattan1990** [comment]
`class Export_model(torch.nn.Module):
    def __init__(self, generate):
        super(Export_model, self).__init__()
        self.generate = generate

    def forward(self, x):
        output = self.generate(x, do_sample=True, max_length=50)
        return output`

として、model.generateをエクスポートする。
（こちらのモデルで推論自体は正しく行えたが、エクスポートする際に内部でエラーが発生）

`Traceback (most recent call last):
  File "C:/Users/stayh/OneDrive/デスクトップ/ax_project/Repositories/japanese-pretrained-models/demo.py", line 49, in <module>
    torch.onnx.export(export_model, input, 'rinna-japanese-gpt2-small.onnx', verbose=True,opset_version=11)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\utils.py", line 458, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\onnx\utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\jit\_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\jit\_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\nn\modules\module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:/Users/stayh/OneDrive/デスクトップ/ax_project/Repositories/japanese-pretrained-models/demo.py", line 17, in forward
    output = self.generate(x, do_sample=True, max_length=50)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\transformers\generation_utils.py", line 1016, in generate
    return self.sample(
  File "C:\Users\stayh\Anaconda3\envs\gpt2\lib\site-packages\transformers\generation_utils.py", line 1508, in sample
    unfinished_sequences = input_ids.new(input_ids.shape[0]).fill_(1)
IndexError: slice() cannot be applied to a 0-dim tensor.`

**Comment by kyakuno** [comment]
gpt2モデルをエクスポートするサンプル
https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/README.md

**Comment by hattan1990** [comment]
・文章生成のデモ（Postprocessing steps : For GPT-2-LM-HEAD model, to generate next 10 words:）
https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/README.md

モデルの読込に関する記載はないが、説明文にGPT2LMHeadModelを使用していることが掛かれているため、
以下のモデルを読み込む。
 model = GPT2LMHeadModel.from_pretrained('gpt2')
→同じ文章を繰り返すだけの出力となり、文章生成（model.generate）のような結果にはならない

**Comment by hattan1990** [comment]
> ```
> class Export_model(torch.nn.Module):
>     def __init__(self, generate):
>         super(Export_model, self).__init__()
>         self.generate = generate
> 
>     def forward(self, x):
>         output = self.generate(x, do_sample=True, max_length=50)
>         return output
> ```
> 
> `torch.onnx.export(export_model, input, 'rinna-japanese-gpt2-small.onnx', verbose=True,opset_version=11)`
> 
> として、model.generateをfowardに置き換えてモデルを構築したがエクスポートの際にエラーが発生。 （こちらのモデルで推論は正しく行えた）

以下の通りモデル定義を変更したところ、エクスポートの途中で強制終了される。
エラーログは特に吐かれていない。
```
class Export_model(torch.nn.Module):
    def __init__(self, generate):
        super(Export_model, self).__init__()
        self.generate = generate

    def forward(self, x):
        output = self.generate(x, do_sample=True, max_length=50, top_k=50, top_p=1.0,num_beams = 2,
                               no_repeat_ngram_size = 2, num_return_sequences = 5, early_stopping = True)
        return output
```

```
 2.1027e-02 -9.6156e-02 -6.1327e-02 -4.4492e-02 -2.8117e-02 -1.8860e-02
-2.7777e-02 -1.6192e-02 -6.6805e-02 -2.1467e-02 -2.6583e-02 -7.5279e-05
 1.0357e-01 -3.2859e-02 -8.5275e-02 -7.3975e-02  7.8316e-03  1.5953e-01
-7.5212e-02 -1.1909e-01 -7.3392e-02 -3.5064e-02  2.6867e-02  1.2215e-01
 1.9359e-01 -2.6407e-01 -1.5513e-01  2.0891e-02 -7.6167e-02  8.5638e-02
[ torch.FloatTensor{32000,768} ]

プロセスは終了コード 1 で終了しました
```

**Comment by kyakuno** [comment]
エクスポートスクリプトは下記のgpt_neoを使用。
https://github.com/oborchers/Medium_Repo/blob/master/Putting%20GPT-Neo%20into%20Production%20using%C2%A0ONNX/ONNX-Export.ipynb

```
import os
os.environ['ORT_TENSORRT_MAX_BATCH_SIZE'] = '10'
os.environ['ORT_TENSORRT_MAX_WORKSPACE_SIZE'] = '4294967296'
os.environ['ORT_TENSORRT_MAX_PARTITION_ITERATIONS'] = '20'
os.environ['ORT_TENSORRT_MIN_SUBGRAPH_SIZE'] = '5'

import torch
import json
import numpy as np
import onnx
import onnxruntime as rt
import multiprocessing
import transformers

from termcolor import colored
from transformers import convert_graph_to_onnx
from pathlib import Path
from sentence_transformers import SentenceTransformer
#from onnxruntime_customops import get_library_path

print(onnx.__version__)
print(rt.__version__)
print(transformers.__version__)

span = "生命、宇宙、そして万物についての究極の疑問の答えは"

ONNX_PROVIDERS = ["CUDAExecutionProvider", "CPUExecutionProvider",]

opt = rt.SessionOptions()
#opt.register_custom_ops_library(get_library_path())
opt.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
opt.log_severity_level = 4
opt.intra_op_num_threads = multiprocessing.cpu_count()
opt.execution_mode = rt.ExecutionMode.ORT_SEQUENTIAL

print(colored(f"GPU available {torch.cuda.is_available()}", "green"))
print(colored(f"GPU Name: {torch.cuda.get_device_name(0)}", "green"))
print(colored(f"GPU Count: {torch.cuda.device_count()}", "green"))
print(colored(f"CORE Count: {multiprocessing.cpu_count()}", "green"))

model_name = "rinna/japanese-gpt2-small"
pipeline_name = "text-generation"

model_pth = Path(f"rinna/japanese-gpt2-small.onnx")
model_pth.parent.mkdir(exist_ok=True, parents=True)

nlp = transformers.pipeline(pipeline_name, model=model_name, tokenizer=model_name)
tokenizer = nlp.tokenizer
model = nlp.model

with torch.no_grad():
    (
        input_names,
        output_names,
        dynamic_axes,
        tokens,
    ) = convert_graph_to_onnx.infer_shapes(nlp, "pt")
    ordered_input_names, model_args = convert_graph_to_onnx.ensure_valid_input(
        nlp.model, tokens, input_names
    )

class GPT2Sent(transformers.GPT2LMHeadModel):
    def __init__(self, config):
        super().__init__(config)
        self.sentence_embedding = torch.nn.Identity()

    def forward(self, input_ids, attention_mask):
        return self.sentence_embedding(
            super().forward(input_ids, attention_mask=attention_mask).logits
        )
# Create the new model based on the config of the original pipeline
model = GPT2Sent(config=nlp.model.config).from_pretrained(model_name)

encoding = nlp.tokenizer([span], return_tensors="pt")

if not model_pth.exists():
    torch.onnx.export(
        model,
        (encoding["input_ids"], encoding["attention_mask"]),
        f=model_pth.as_posix(),
        input_names=input_names,
        do_constant_folding=True,
        use_external_data_format=True,
        enable_onnx_checker=True,
        opset_version=11,
    )
```

**Comment by kyakuno** [comment]
use_external_data_formatをTrueにすると、weightが別ファイルに分離されてしまうので、Falseに設定する必要がある。また、上記のエクスポートコードだと、入力のセンテンスの長さが固定されてしまうので、dynamic_axesを使用する。

```
        inputs = ['input_ids','attension_mask']
        outputs = ['3062']
        dynamic_axes = {'input_ids': {1: 'len'}, 'attension_mask': {1: 'len'}, '3062': {1: 'len'}}

        torch.onnx.export(
            model,
            (encoding["input_ids"], encoding["attention_mask"]),
            f=model_pth.as_posix(),
            input_names=input_names,
            do_constant_folding=True,
            use_external_data_format=False,
            enable_onnx_checker=True,
            opset_version=11,
            dynamic_axes=dynamic_axes
        )
```

**Comment by kyakuno** [comment]
センテンスを「こんにちは」として、input_idsが(1, 4)の場合、出力は(1, 4, 32000)となる。これは、input_idsの各要素に対応する、32000ワードのそれぞれの出現確率である。ここから、[0,-1,:]の最大確率のワードを取得し、input_idsにappendして推論する、ということを繰り返すことで、文章が生成される。

**Comment by kyakuno** [comment]
最大確率をそのまま使用するのではなく、ランダムサンプリングをすることで、より精度を高めることもできる。
https://zenn.dev/tyaahan/articles/a8d99900000002

**Comment by kyakuno** [comment]
rinnaのtokenizerはsentencepieceを使用している。
https://github.com/google/sentencepiece
https://github.com/rinnakk/japanese-pretrained-models/blob/master/data/tokenizer/google_sp.vocab
