### ISSUE TITLE
ADD cosface

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#599]
https://github.com/MuggleWang/CosFace_pytorch
mit

**Comment by kyakuno** [comment]
モデルのダウンロードにBaiduDriveが必要。

**Comment by kyakuno** [comment]
Downloaded pth model (Licensed under https://github.com/MuggleWang/CosFace_pytorch/blob/master/LICENSE)
https://storage.googleapis.com/ailia-models/cosface/ACC99.28.pth

**Comment by masa8** [comment]
Let me take a look.
