### ISSUE TITLE
WIP 3d DNN 

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#61]
ref: https://qiita.com/arutema47/items/cda262c61baa953a97e9

**Comment by sngyo** [comment]
この辺りから選べば良さそう？

- https://github.com/facebookresearch/votenet
- https://github.com/fxia22/pointnet.pytorch
- https://github.com/erikwijmans/Pointnet2_PyTorch
- https://github.com/traveller59/second.pytorch

**Comment by ooe1123** [comment]
○ PointNet.pytorch
学習済みのモデルが提供されていないため、学習から行う必要がある。
3Dデータを推論するため、デモを行うためにはインタラクティブに物体の回転ができるビジュアル機能があったほうがよさそう。
リポジトリでビジュアル機能が提供されているが、Pythonのみではなく、バイナリコンパイルしたC++の共有ライブラリを使っている。
![image](https://user-images.githubusercontent.com/29946532/100514515-c859bd80-31b8-11eb-8687-db45f41fd070.png)

**Comment by ooe1123** [comment]
○ PointNet.pytorch
Widowns用のビジュアル機能の共有ライブラリ（render_balls_so.cpp）のコンパイル方法。
CMakeLists.txt を作り、cmakeを実行すると.slnが作成されるので、VisutalStudioでコンパイルを行う。

[CMakeLists.txt]
```
cmake_minimum_required(VERSION 3.3)

project(DLL)

add_library(${PROJECT_NAME} SHARED render_balls_so.cpp)
```
[render_balls_so.cpp]
```
#include <cstdio>
#include <vector>
#include <algorithm>
#include <math.h>
using namespace std;

#define DLL_EXPORT __declspec(dllexport)

struct PointInfo{
	int x,y,z;
	float r,g,b;
};

extern "C"{

DLL_EXPORT void render_ball(int h,int w,unsigned char * show,int n,int * xyzs,float * c0,float * c1,float * c2,int r){
    ....
}

}//extern "C"
```

**Comment by ooe1123** [comment]
○ PointNet.pytorch
onnx.export時のエラーを回避するため、以下を修正する。
[model.py]
```
class PointNetCls(nn.Module):
    def forward(self, x):
        ...
        # return F.log_softmax(x, dim=1), trans, trans_feat ←--- コメントアウト
        return F.log_softmax(x, dim=1), trans # ←--- 追記

class PointNetDenseCls(nn.Module):
    def forward(self, x):
        ...
        # return x, trans, trans_feat ←--- コメントアウト
        return x, trans # ←--- 追記
```

**Comment by kyakuno** [comment]
PointNet.pytorchに対応したためClose。
