### ISSUE TITLE
ADD FERPlus

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#628]
CNTKからのONNXエクスポートの練習として。
https://github.com/microsoft/FERPlus

**Comment by kyakuno** [comment]
CNTKはWindowsとLinuxでしか動作しない。
また、学習済みモデルはないので1から再学習する必要。

**Comment by ooe1123** [comment]
○ ONNX保存
cntkのモデルからonnxに保存することが可能
```
# get the probalistic output of the model.
z    = model.model(input_var)
print(">>>", z)
z.save("myModel.onnx", format=ct.ModelFormat.ONNX)
```
```
>>> output: Composite(Tensor[1,64,64]) -> Tensor[8]
```

**Comment by ooe1123** [comment]
○ データセットの準備
1. fer2013.tar.gz をダウンロード
2. `mv fer2013.tar.gz data`
3. `cd data && tar zxvf fer2013.tar.gz`
4. `python src/generate_training_data.py -d data -fer data/fer2013/fer2013.csv -ferplus fer2013new.csv`

○ 学習実行
`python3.6 src/train.py -d data -m majority`

**Comment by ooe1123** [comment]
Colaboratoryで実行する場合、共有ライブラリのエラーが発生するため、以下のようにして解決する
```
ln -s /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20.10.0 /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.1
ln -s /usr/lib/x86_64-linux-gnu/libmpi.so.20 /usr/lib/x86_64-linux-gnu/libmpi.so.12
```
