### ISSUE TITLE
ADD awesome-crowd-counting

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#64]
[Awesome-Crowd-Counting](https://github.com/gjy3035/Awesome-Crowd-Counting)

**Comment by ooe1123** [comment]
○ C-3-Framework（https://github.com/gjy3035/C-3-Framework）
公開されている学習済みモデルはそのままではモデルロードできない。以下を参考に変換が必要
https://github.com/gjy3035/C-3-Framework/issues/64

**Comment by ooe1123** [comment]
○ C-3-Framework
学習済みモデルを使うには以下の設定を行う。
① test.pyのmodel_path変数にモデルのパスを設定する
② config.pyの__C.NET = 'xxx' の行を修正して、学習済みモデルに合ったモデルを設定する。

- 02-AlexNet_all_ep_83_mae_46.3_mse_110.9.pth ... AlexNet
- 03-VGG_all_ep_32_mae_36.6_mse_88.9.pth ... VGG
- 04-VGG_decoder_all_ep_21_mae_37.2_mse_91.2.pth ... VGG_DECODER
- 05-ResNet-50_all_ep_35_mae_32.4_mse_76.1.pth ... Res50
- 06-ResNet-101_all_ep_35_mae_31.9_mse_81.4.pth ... Res101
- 07-CSRNet_all_ep_39_mae_32.6_mse_74.3.pth ... CSRNet
- 11-ResSFCN-101_all_ep_94_mae_26.8_mse_66.1.pth ... Res101_SFCN

**Comment by ooe1123** [comment]
○ C-3-Framework
学習済みモデルの08-SANet_all_ep_57_mae_42.4_mse_85.4.pth を使う場合、以下の修正を行う。

test.py
```
# from models.CC import CrowdCounter
from models.M2TCC import CrowdCounter
```
```
# net = CrowdCounter(cfg.GPU_ID,cfg.NET)
loss_1_fn = nn.MSELoss()
from misc import pytorch_ssim
loss_2_fn = pytorch_ssim.SSIM(window_size=11)
net = CrowdCounter(cfg.GPU_ID,cfg.NET,loss_1_fn,loss_2_fn)
```

**Comment by ooe1123** [comment]
○ C-3-Framework
11-ResSFCN-101_all_ep_94_mae_26.8_mse_66.1.pth のONNXエクスポートは以下のエラーがでるため断念
```
RuntimeError: ONNX export failed: Couldn't export Python operator Resize

Defined at:
/home/ooe/env1/lib/python3.7/site-packages/torch/tensor.py(449): resize
/home/ooe/C3/C-3-Framework/misc/layer.py(66): forward
/home/ooe/env1/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/home/ooe/env1/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/home/ooe/C3/C-3-Framework/models/SCC_Model/Res101_SFCN.py(50): forward
/home/ooe/env1/lib/python3.7/site-packages/torch/nn/modules/module.py(709): _slow_forward
/home/ooe/env1/lib/python3.7/site-packages/torch/nn/modules/module.py(725): _call_impl
/home/ooe/C3/C-3-Framework/models/CC.py(48): test_forward
```
