### ISSUE TITLE
ADD pixel-link

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#65]
[pixel-link](https://github.com/ZJULearning/pixel_link): 画像内の文字のdetection

**Comment by ooe1123** [comment]
https://github.com/ZJULearning/pixel_link のコードだと、検知ができていなかった。
報告されているこれらのissueと同じ？
- https://github.com/ZJULearning/pixel_link/issues/130
- https://github.com/ZJULearning/pixel_link/issues/146

このリポジトリのforkである
https://github.com/baby313/pixel_link
を使うと、正しく検知ができた。
