### ISSUE TITLE
LightWeightHumanPose3Dのカメラ入力解像度の変更

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#69]
Jetsonの場合、Webカメラデバイスとして(448,256)が使用できない。Webカメラとしてはデフォルト解像度で取得して、推論時にリサイズした方が良さそう。
https://github.com/axinc-ai/ailia-models/commit/e212b324082e2b51228df4885a5f1a4647bf0277#diff-cd2c7a727abed0b954278ec78ebff684

**Comment by kyakuno** [comment]
メインスクリプトでresizeしているので、set_capsをコメントアウトするだけで良さそう。

**Comment by sngyo** [comment]
確認後，修正して次回のリファクタ PRに合わせてアップデートします
