### ISSUE TITLE
How to convert OpenVINO  model to onnx?

### ISSUE THREAD

**Issue by zhongwenkun886** [axinc-ai/ailia-models#756]
I want to know how to convert OpenVINO model to onnx, such as the model of vehicle-license-plate-detection-barrier in this project.
Thank you very much.

**Comment by kyakuno** [comment]
You can use openvino2tensorflow.

```
openvino2tensorflow --model_path vehicle-license-plate-detection-barrier-0106.xml --output_saved_model --output_onnx --onnx_opset 11
```

https://github.com/axinc-ai/ailia-models/issues/568

**Comment by zhongwenkun886** [comment]
thanks
