### ISSUE TITLE
yolov1_faceの出力がREADMEと異なる

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#79]
- 出力画像は下記の通り (masterブランチの実行で確認)
- 環境 MacBookPro2017, ailia version `1.2.1.617-rc04eea2`
![tmp](https://user-images.githubusercontent.com/45060776/80276036-9ebb4e00-8720-11ea-8f03-096ae42ca778.png)

- ailiaのバグなら修正を，正常に動いているようであればREADMEの画像の差し替えが必要

**Comment by sngyo** [comment]
- yolov1-tinyも異なる様子
![tmp](https://user-images.githubusercontent.com/45060776/80276741-987ba080-8725-11ea-8150-c93c94c83743.png)

- videoモードでは正常に動いているようなので，単純にモデルの精度の問題かもしれない

**Comment by kyakuno** [comment]
ailia SDK 1.2.2 + MacBookPro 13 では正常に動作しました。

![output](https://user-images.githubusercontent.com/38881041/80324353-7db34400-886b-11ea-9709-9cf1ec510914.png)
![output](https://user-images.githubusercontent.com/38881041/80324357-8277f800-886b-11ea-82da-bb2c2cd16691.png)

**Comment by sngyo** [comment]
1.2.2での動作が確認できたのでclose
