### ISSUE TITLE
ADD NDL OCR

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#820]
https://github.com/ndl-lab/text_recognition

**Comment by ooe1123** [comment]
https://github.com/ndl-lab/ndlocr_cli
NDLOCRは、こちらの統合ソリューションで利用されるモジュールの一つ。

データセットが不明なので、
単体で動かすよりは、ndlocr_cliから呼び出したほうが動作確認を行いやすい。
