### ISSUE TITLE
requirements.txtの準備

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#84]
大きく2通りの手法が考えられる

## 全てのモデルを動かせるようにあらゆるモデルで使用されているライブラリを一括でinstallできるようにする
- (+) 管理および作成が楽
- (-) マイナーなライブラリを使用していたりすると多くの場合必要としないのにinstallされてしまう可能性がある

## モデルごとに個別にrequirements.txt を作成する
- (+) 個別に管理できるので必要とされるライブラリは少なくて済む
- (-) 一つ一つ作成しないといけないので少し手間がかかる

**Comment by kyakuno** [comment]
全体で一つのrequirementsにして頂いて、できるだけ個別リポジトリの依存関係を減らす、という方向でお願いできればと思います。

**Comment by sngyo** [comment]
https://github.com/axinc-ai/ailia-models/pull/87
