### ISSUE TITLE
ADD WeChatQRCode

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#842]
https://github.com/opencv/opencv_zoo/tree/4fb591053ba1201c07c68929cc324787d5afaa6c/models/qrcode_wechatqrcode

**Comment by kyakuno** [comment]
Apache

**Comment by kyakuno** [comment]
https://github.com/luxonis/depthai-model-zoo/tree/main/models/qr_code_detection_384x384

**Comment by kyakuno** [comment]
caffemodelのままailiaで読めるか要検証。

**Comment by yuki399** [comment]
利用しているcaffemodel2つともailia sdkで動作しません

sr.caffemodel
Unsupported layer: Permute

detect.caffemodel
Layer:nearest(Deconvolution) Error:Unsupported axis value. (Neither X to W)

**Comment by kyakuno** [comment]
@yuki399 了解しました。ailia SDK側で読めるように対応しようと思うので、とりあえず、OpenCVのinference engineを使う形で、サンプルを作成いただけますでしょうか？

**Comment by yuki399** [comment]
わかりました
そのように進めます

**Comment by kyakuno** [comment]
将来的には下記のC++のサンプルをPythonに移植したい。
https://github.com/opencv/opencv_contrib/tree/db16caf6ceee76b43b94c846be276e92a43e9700/modules/wechat_qrcode/src

**Comment by kyakuno** [comment]
現状は、OpenCVのcontribの中の前処理と後処理（SSD）に強く依存している。このあたりの前処理と後処理をPythonに持っていって、OpenCVの単純なcaffemodelのinferenceで動くようにしたい。

**Comment by kyakuno** [comment]
netのoutputは意外とシンプルで複雑な後処理は不要。
shape is (1,1,100,7)=>(batch,channel,count,dim)
