### ISSUE TITLE
ADD StableDiffusion

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#900]
https://github.com/CompVis/stable-diffusion

**Comment by gettest255** [comment]
I think the pretrained model is not published yet.

**Comment by yuananf** [comment]
Model is published today. And also check https://github.com/huggingface/diffusers

**Comment by kyakuno** [comment]
onnx
https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx

**Comment by kyakuno** [comment]
pipeline
https://github.com/mystic-ai/pipeline/blob/paul/stable-diffusion/examples/custom_models/stable_diffusion.py

**Comment by kyakuno** [comment]
openvino
https://github.com/bes-dev/stable_diffusion.openvino

**Comment by kyakuno** [comment]
openvino
https://huggingface.co/bes-dev/stable-diffusion-v1-4-openvino

**Comment by Baiyuetribe** [comment]
is'it work?
https://github.com/MerijnvanEijk/stbl-diffusion-gui-onnx

**Comment by kyakuno** [comment]
@ooe1123 StableDiffusionのエクスポートの手順につきまして、どのリポジトリを使用したかの情報をいただくことは可能でしょうか。また、可能であれば、エクスポートに使用したリポジトリを、axincのリポジトリにpublic forkいただければと考えています。

**Comment by kyakuno** [comment]
目的は下記のIssueの実装となります。
https://github.com/axinc-ai/ailia-models/issues/1091

**Comment by ooe1123** [comment]
@kyakuno 
こちらのリポジトリで、
https://github.com/CompVis/stable-diffusion
どのリビジョンだったかはっきりとは分からないのですが、
時期的に考えて以下の時点のコミットなのではないかと思います。
```
Date:   23 8 2022 01:57:55 +09:00
```
