### ISSUE TITLE
CLIP & ActionCLIP high memory usage

### ISSUE THREAD

**Issue by zhaochow** [axinc-ai/ailia-models#903]
Running an inference with the text encoder module of CLIP based models yields a very high memory usage compared to the input tensor size or model size and can lead to OOM error.

CLIP:

- 400 input text labels
- Input: int64 tensor of shape (400, 77), ~246 KB
- Output: float32 tensor of shape (400, 512), ~819 KB
- Model weights size: 254.1 MB
- Memory usage: ~60 GB
- Code: https://github.com/axinc-ai/ailia-models/blob/9ad8eebe0020abc1954d8a5efbffb9c016a2850f/image_classification/clip/clip.py#L137-L141

ActionCLIP:

- 400 input text labels
- Input: int64 tensor of shape (16*400, 77), ~3.9 MB
- Output: float32 tensor of shape (16*400, 512), ~13.1 MB
- Model weights size: 254.1 MB
- Memory usage: more than 70 GB (program crashed before getting the output)
- Code: https://github.com/axinc-ai/ailia-models/blob/9ad8eebe0020abc1954d8a5efbffb9c016a2850f/action_recognition/action_clip/action_clip.py#L179

The above numbers were observed on a MacBook Pro M1 2020 with 16 GB of memory

**Comment by kyakuno** [comment]
We implemented memory mode to ailia SDK.

```
        memory_mode = ailia.get_memory_mode(
            reduce_constant=True, ignore_input_with_initializer=True,
            reduce_interstage=False, reuse_interstage=False)
```

Currently we only need 1.26GB for CLIP embedding.
And we implemented batch_size_limit = 16 for text embedding.
