### ISSUE TITLE
ADD pytorch-superpoint

### ISSUE THREAD

**Issue by miyamotost** [axinc-ai/ailia-models#918]

**Comment by miyamotost** [comment]
https://github.com/eric-yyjau/pytorch-superpoint

**Comment by miyamotost** [comment]
https://github.com/axinc-ai/ailia-models/issues/766 で必要

**Comment by miyamotost** [comment]
プルリクエスト発行済み

**Comment by masa8** [comment]
This is obviously closed, right?
Closed to make it easier to find tasks 😆
