### ISSUE TITLE
ADD e4e

### ISSUE THREAD

**Issue by wkzhao** [axinc-ai/ailia-models#924]
https://github.com/omertov/encoder4editing

**Comment by hattan1990** [comment]
psp.pyで定義されているモデルのdecoder部分がカーネル関数（.cpp、.cuファイルで実装）で書かれているため、
エクスポート方法を工夫する必要がある。
https://github.com/omertov/encoder4editing/tree/main/models/stylegan2/op

**Comment by hattan1990** [comment]
また、`torch.autograd.Functions`とTorchScriptが組み合わされているためエクスポートは困難。

**Comment by ooe1123** [comment]
cuda extension の実装は
https://github.com/yangxy/GPEN/tree/main/face_model/op 
の実装で置き換え可能

**Comment by ooe1123** [comment]
onnxエクスポート

[encoder]
○ models/psp.py
```
class pSp(nn.Module):
    ...
    def forward(self, x, resize=True, latent_mask=None, input_code=False, randomize_noise=True,
                inject_latent=None, return_latents=False, alpha=None):
        ...
        images, result_latent = self.decoder([codes],
                                             input_is_latent=input_is_latent,
                                             randomize_noise=randomize_noise,
                                             return_latents=return_latents)
        ...
```
↓
```
class pSp(nn.Module):
    ...
    def forward(self, x, resize=True, latent_mask=None, input_code=False, randomize_noise=False,
                inject_latent=None, return_latents=True, alpha=None):
        ...
        images, result_latent = self.decoder([codes],
                                             input_is_latent=input_is_latent,
                                             randomize_noise=randomize_noise,
                                             return_latents=return_latents)
        return images, result_latent
        ...
```

[decoder]
○ models/psp.py
```
class pSp(nn.Module):
    ...
    def forward(self, x, resize=True, latent_mask=None, input_code=False, randomize_noise=True,
                inject_latent=None, return_latents=False, alpha=None):
        ...
        images, result_latent = self.decoder([codes],
                                             input_is_latent=input_is_latent,
                                             randomize_noise=randomize_noise,
                                             return_latents=return_latents)
        ...
```
↓
```
class pSp(nn.Module):
    ...
    def forward(self, x, resize=True, latent_mask=None, input_code=False, randomize_noise=True,
                inject_latent=None, return_latents=False, alpha=None):
        ...
        images, result_latent = self.decoder([codes],
                                             input_is_latent=input_is_latent,
                                             randomize_noise=randomize_noise,
                                             return_latents=return_latents)

        print("------>")
        from torch.autograd import Variable
        self.decoder.forward = self.decoder.forward2
        codes = Variable(codes)
        torch.onnx.export(
            self.decoder, codes, 'decoder.onnx',
            input_names=["latent"],
            output_names=["image"],
            verbose=True, opset_version=12
        )
        print("<------")
```

○ models/stylegan2/model.py
class Generator(nn.Module):
    ...
    def forward2(
            self,
            latent
    ):
        noise = [
            getattr(self.noises, f'noise_{i}') for i in range(self.num_layers)
        ]
        out = self.input(latent)
        out = self.conv1(out, latent[:, 0], noise=noise[0])
        skip = self.to_rgb1(out, latent[:, 1])
        shapes = [
            [1, 512, 8, 8],
            [1, 512, 16, 16],
            [1, 512, 32, 32],
            [1, 512, 64, 64],
            [1, 256, 128, 128],
            [1, 128, 256, 256],
            [1, 64, 512, 512],
            [1, 32, 1024, 1024],
        ]

        i = 1
        for conv1, conv2, noise1, noise2, to_rgb in zip(
                self.convs[::2], self.convs[1::2], noise[1::2], noise[2::2], self.to_rgbs
        ):
            out = conv1(out, latent[:, i], noise=noise1)
            out = out.reshape(shapes[i//2])
            out = conv2(out, latent[:, i + 1], noise=noise2)
            skip = to_rgb(out, latent[:, i + 2], skip)
            i += 2

        image = skip
        return image
