### ISSUE TITLE
Use GPU for Blazepose 3D pose estimation

### ISSUE THREAD

**Issue by ongsici** [axinc-ai/ailia-models#937]
I'm trying to run Blazepose 3D pose estimation and only able to get it to run on my CPU. How can I get it to run on my GPU instead as I have several videos to run please? Thanks!

**Comment by kyakuno** [comment]
What environment are you using? For Jetson Orin, ailia SDK 1.2.12 does not support Orin's GPU. Orin compatible version of ailia SDK 1.2.13 will be released tomorrow.

**Comment by ongsici** [comment]
i'm using Ubuntu 20.04
